#!/bin/bash

# ============================================================================
# Purpose:     Run test of bundle_tex_figures.sh on sample input.
# Usage:       ./test_bundle.sh
# Input:       test/sample.tex, test/fig1.png
# Output:      bundle zip file or dry run output
# Date:        2025-05-02
# Version:     1.0
# Chat name:   Bishop Bash
# GPT Model:   GPT-4
# Generated by Michael Gilchrist in collaboration with ChatGPT
# ============================================================================

cd "$(dirname "$0")/.."

# Dry run test
echo "Running dry run test..."
./bundle_tex_figures.sh -n test/sample.tex

# Full run test
echo "Running actual archive creation..."
./bundle_tex_figures.sh test/sample.tex
