#!/usr/bin/env python3
# ============================================================================
# Script:       test_update_bib.py
# Version:      1.0.0
# Date:         2026-03-24
# Purpose:      Test suite for update.bib.py core functions
#
# Tests cover: author parsing, key generation, filename generation,
# title cleaning, protected words, BibTeX title protection, journal
# abbreviation lookup, BibTeX/RIS parsing, and --update-journals mode.
#
# Usage:        pytest test/test_update_bib.py [-v]
# Input:        None (self-contained test data)
# Output:       pytest results
#
# Requirements:
#   - pytest
#   - update.bib.py in parent directory
#
# Session:      BibTeX Test Suite
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

import importlib.util
import os
import sys
import tempfile
import textwrap

import pytest

# ---------------------------------------------------------------------------
# Import update.bib.py (filename has dots, so use importlib)
# ---------------------------------------------------------------------------

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_SCRIPT = os.path.join(_REPO_ROOT, "update.bib.py")

spec = importlib.util.spec_from_file_location("update_bib", _SCRIPT)
ub = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ub)


# ===========================================================================
# Author parsing
# ===========================================================================

class TestParseAuthors:
    """Tests for parse_authors()."""

    def test_single_author_comma_format(self):
        result = ub.parse_authors("Smith, John")
        assert len(result) == 1
        assert result[0][0] == "Smith"
        assert result[0][1] == "J."

    def test_single_author_initials(self):
        result = ub.parse_authors("Smith, J. K.")
        assert result[0] == ("Smith", "J. K.")

    def test_two_authors(self):
        result = ub.parse_authors("Smith, J. and Jones, K.")
        assert len(result) == 2
        assert result[0][0] == "Smith"
        assert result[1][0] == "Jones"

    def test_three_authors(self):
        result = ub.parse_authors("Smith, J. and Jones, K. and Lee, M.")
        assert len(result) == 3
        assert result[2][0] == "Lee"

    def test_all_caps_surname(self):
        """Surnames in ALL CAPS should be title-cased."""
        result = ub.parse_authors("SMITH, J.")
        assert result[0][0] == "Smith"

    def test_mc_prefix(self):
        """McDonald should preserve Mc + capital."""
        result = ub.parse_authors("MCDONALD, J.")
        assert result[0][0] == "McDonald"

    def test_empty_input(self):
        assert ub.parse_authors("") == []
        assert ub.parse_authors(None) == []

    def test_natural_order_format(self):
        """'Firstname Surname' format (no comma)."""
        result = ub.parse_authors("John Smith")
        assert result[0][0] == "Smith"
        assert result[0][1] == "J."

    def test_single_name(self):
        """Single-word name with no comma."""
        result = ub.parse_authors("Consortium")
        assert result[0][0] == "Consortium"
        assert result[0][1] == ""


# ===========================================================================
# Key generation
# ===========================================================================

class TestGenerateKey:
    """Tests for generate_key()."""

    def test_single_author(self):
        authors = [("Smith", "J.")]
        assert ub.generate_key(authors, "2012") == "Smith2012"

    def test_two_authors(self):
        authors = [("Smith", "J."), ("Jones", "K.")]
        assert ub.generate_key(authors, "2012") == "SmithAndJones2012"

    def test_three_authors(self):
        authors = [("Smith", "J."), ("Jones", "K."), ("Lee", "M.")]
        assert ub.generate_key(authors, "2012") == "SmithEtAl2012"

    def test_no_authors(self):
        assert ub.generate_key([], "2012") == "Unknown2012"

    def test_special_chars_stripped(self):
        """Non-alphanumeric chars in surname should be stripped from key."""
        authors = [("O'Brien", "J.")]
        assert ub.generate_key(authors, "2012") == "OBrien2012"

    def test_hyphenated_surname(self):
        authors = [("Garcia-Lopez", "M.")]
        assert ub.generate_key(authors, "2020") == "GarciaLopez2020"


# ===========================================================================
# Filename generation
# ===========================================================================

class TestGenerateFilename:
    """Tests for generate_filename()."""

    def test_single_author(self):
        authors = [("Smith", "J.")]
        fn = ub.generate_filename(authors, "2012", "A Novel Approach", "Nature")
        assert fn == "Smith_2012_a.novel.approach_Nature.pdf"

    def test_two_authors(self):
        authors = [("Smith", "J."), ("Jones", "K.")]
        fn = ub.generate_filename(authors, "2012", "Some Title", "Science")
        assert fn == "Smith.and.Jones_2012_some.title_Science.pdf"

    def test_three_authors(self):
        authors = [("Smith", "J."), ("Jones", "K."), ("Lee", "M.")]
        fn = ub.generate_filename(authors, "2012", "Some Title", "Nature")
        assert fn == "Smith.et.al_2012_some.title_Nature.pdf"

    def test_no_journal(self):
        authors = [("Smith", "J.")]
        fn = ub.generate_filename(authors, "2012", "Some Title", "")
        assert fn == "Smith_2012_some.title.pdf"

    def test_pnas_abbreviation(self):
        """Very long journal names should use custom abbreviations."""
        authors = [("Smith", "J.")]
        fn = ub.generate_filename(
            authors, "2012", "Some Title",
            "Proceedings Of The National Academy Of Sciences Of The United States Of America"
        )
        assert "_PNAS.pdf" in fn

    def test_protected_words_in_title(self):
        """DNA, mRNA etc. should preserve case in filename."""
        authors = [("Smith", "J.")]
        fn = ub.generate_filename(authors, "2012", "DNA Replication in E. coli", "Nature")
        assert "DNA" in fn

    def test_no_authors(self):
        fn = ub.generate_filename([], "2012", "Title", "Nature")
        assert fn.startswith("Unknown_2012_")

    def test_apostrophe_removed(self):
        authors = [("Smith", "J.")]
        fn = ub.generate_filename(authors, "2012", "Parkinson's Disease", "Nature")
        assert "'" not in fn
        assert "parkinsons" in fn.lower()


# ===========================================================================
# Title cleaning
# ===========================================================================

class TestCleanTitleForFilename:
    """Tests for _clean_title_for_filename()."""

    def test_basic_lowercasing(self):
        """_clean_title_for_filename lowercases but keeps spaces.
        Periods are added later by _sanitize_filename."""
        result = ub._clean_title_for_filename("The Quick Brown Fox")
        assert result == "the quick brown fox"

    def test_preserves_all_caps(self):
        """ALL-CAPS acronyms like DNA should not be lowercased."""
        result = ub._clean_title_for_filename("DNA Replication")
        assert "DNA" in result

    def test_preserves_mixed_case_protected(self):
        """Protected words like mRNA should keep their case."""
        result = ub._clean_title_for_filename("Analysis of mRNA Stability")
        assert "mRNA" in result

    def test_trailing_period_removed(self):
        result = ub._clean_title_for_filename("Some Title.")
        assert not result.endswith(".")

    def test_leading_article_lowered(self):
        """'A Novel Approach' -> 'a novel approach'."""
        result = ub._clean_title_for_filename("A Novel Approach")
        assert result.startswith("a ")


# ===========================================================================
# BibTeX title protection
# ===========================================================================

class TestProtectBibtexTitle:
    """Tests for protect_bibtex_title()."""

    def test_dna_wrapped(self):
        result = ub.protect_bibtex_title("DNA replication in cells")
        assert "{DNA}" in result
        assert "replication" in result  # non-protected word untouched

    def test_mrna_wrapped(self):
        result = ub.protect_bibtex_title("Analysis of mRNA stability")
        assert "{mRNA}" in result

    def test_already_braced_not_doubled(self):
        result = ub.protect_bibtex_title("{DNA} replication")
        # Should not get {{DNA}}
        assert "{{DNA}}" not in result

    def test_multiple_protected_words(self):
        result = ub.protect_bibtex_title("DNA and RNA in CRISPR systems")
        assert "{DNA}" in result
        assert "{RNA}" in result
        assert "{CRISPR}" in result

    def test_empty_title(self):
        assert ub.protect_bibtex_title("") == ""
        assert ub.protect_bibtex_title(None) is None

    def test_no_protected_words(self):
        """Title with no protected words should be returned unchanged."""
        result = ub.protect_bibtex_title("A simple title about nothing")
        assert result == "A simple title about nothing"


# ===========================================================================
# Journal abbreviation lookup
# ===========================================================================

class TestJournalAbbreviations:
    """Tests for JournalAbbreviations class."""

    def test_basic_lookup(self):
        abbrev = ub._journal_db.get_abbreviation("Molecular Biology and Evolution")
        assert abbrev is not None
        assert abbrev == "Mol. Biol. Evol."

    def test_case_insensitive(self):
        a1 = ub._journal_db.get_abbreviation("molecular biology and evolution")
        a2 = ub._journal_db.get_abbreviation("MOLECULAR BIOLOGY AND EVOLUTION")
        assert a1 == a2

    def test_leading_the_stripped(self):
        """'The FEBS Journal' and 'FEBS Journal' should match."""
        a1 = ub._journal_db.get_abbreviation("The FEBS Journal")
        a2 = ub._journal_db.get_abbreviation("FEBS Journal")
        assert a1 == a2

    def test_bibtex_braces_stripped(self):
        """Journal names with {braces} should match after stripping."""
        abbrev = ub._journal_db.get_abbreviation("{BMC} Bioinformatics")
        assert abbrev is not None
        assert "BMC" in abbrev

    def test_latex_ampersand_normalized(self):
        r"""Journal names with \& should match."""
        abbrev = ub._journal_db.get_abbreviation(r"Trends In Ecology \& Evolution")
        assert abbrev is not None

    def test_supplementary_entry(self):
        """Journals in SUPPLEMENTARY_JOURNAL_ABBREVS should be found."""
        abbrev = ub._journal_db.get_abbreviation("Nature Communications")
        assert abbrev == "Nat. Commun."

    def test_supplementary_elife(self):
        abbrev = ub._journal_db.get_abbreviation("eLife")
        assert abbrev == "eLife"

    def test_reverse_lookup(self):
        """Already-abbreviated names should return canonical abbreviation."""
        abbrev = ub._journal_db.get_abbreviation("Proc Natl Acad Sci U S A")
        assert abbrev is not None

    def test_not_found_returns_none(self):
        abbrev = ub._journal_db.get_abbreviation("Fake Journal Of Nonsense")
        assert abbrev is None

    def test_get_full_name(self):
        full = ub._journal_db.get_full_name("Mol. Biol. Evol.")
        assert full is not None
        assert "Molecular" in full

    def test_trailing_comma_stripped(self):
        """Journal names with trailing comma should still match."""
        abbrev = ub._journal_db.get_abbreviation("Annual Review of Genetics,")
        assert abbrev is not None


# ===========================================================================
# BibTeX string parsing
# ===========================================================================

class TestParseBibtexString:
    """Tests for parse_bibtex_string()."""

    def test_single_entry(self):
        bib = textwrap.dedent("""\
            @article{Smith2012,
                author = {Smith, J. and Jones, K.},
                title = {A test article},
                journal = {Nature},
                year = {2012},
                volume = {42},
                pages = {1-15}
            }
        """)
        entries = ub.parse_bibtex_string(bib)
        assert len(entries) == 1
        e = entries[0]
        assert e["entry_type"] == "article"
        assert "Smith" in e["author"]
        assert e["year"] == "2012"
        assert e["journal"] == "Nature"

    def test_multiple_entries(self):
        bib = textwrap.dedent("""\
            @article{One2012,
                author = {One, A.},
                title = {First},
                year = {2012}
            }
            @article{Two2013,
                author = {Two, B.},
                title = {Second},
                year = {2013}
            }
        """)
        entries = ub.parse_bibtex_string(bib)
        assert len(entries) == 2

    def test_nested_braces(self):
        """Field values with nested braces should parse correctly."""
        bib = textwrap.dedent("""\
            @article{Test2012,
                author = {Smith, J.},
                title = {Analysis of {DNA} replication},
                year = {2012}
            }
        """)
        entries = ub.parse_bibtex_string(bib)
        assert len(entries) == 1
        assert "{DNA}" in entries[0]["title"] or "DNA" in entries[0]["title"]

    def test_empty_string(self):
        entries = ub.parse_bibtex_string("")
        assert entries == []


# ===========================================================================
# Regex parser specifically
# ===========================================================================

class TestRegexParser:
    """Tests for _parse_with_regex() fallback parser."""

    def test_basic_parsing(self):
        bib = textwrap.dedent("""\
            @article{Smith2012,
                author = {Smith, J.},
                title = {Test title},
                year = {2012}
            }
        """)
        entries = ub._parse_with_regex(bib)
        assert len(entries) == 1
        assert entries[0]["author"] == "Smith, J."
        assert entries[0]["year"] == "2012"

    def test_bare_number_field(self):
        bib = textwrap.dedent("""\
            @article{Test2012,
                author = {Smith, J.},
                year = 2012,
                volume = 42
            }
        """)
        entries = ub._parse_with_regex(bib)
        assert entries[0]["year"] == "2012"
        assert entries[0]["volume"] == "42"

    def test_quoted_values(self):
        bib = textwrap.dedent("""\
            @article{Test2012,
                author = "Smith, J.",
                title = "A test",
                year = {2012}
            }
        """)
        entries = ub._parse_with_regex(bib)
        assert entries[0]["author"] == "Smith, J."


# ===========================================================================
# Update journal-iso (in-place bib file modification)
# ===========================================================================

class TestUpdateJournalIso:
    """Tests for update_journal_iso()."""

    def test_fills_empty_journal_iso(self):
        """Empty journal-iso = {} should be filled in."""
        bib_content = textwrap.dedent("""\
            @article{Smith2012,
                author      = {Smith, J.},
                title       = {Test},
                journal     = {Molecular Biology and Evolution},
                journal-iso = {},
                year        = {2012}
            }
        """)
        with tempfile.NamedTemporaryFile(mode="w", suffix=".bib",
                                         delete=False) as f:
            f.write(bib_content)
            f.flush()
            path = f.name

        try:
            total, updated, skipped, not_found = ub.update_journal_iso(
                path, dry_run=False, verbose=False
            )
            assert updated == 1
            assert skipped == 0

            with open(path) as f:
                result = f.read()
            assert "Mol. Biol. Evol." in result
        finally:
            os.unlink(path)

    def test_inserts_missing_journal_iso(self):
        """If journal-iso field is entirely absent, insert it."""
        bib_content = textwrap.dedent("""\
            @article{Smith2012,
                author      = {Smith, J.},
                title       = {Test},
                journal     = {Nature},
                year        = {2012}
            }
        """)
        with tempfile.NamedTemporaryFile(mode="w", suffix=".bib",
                                         delete=False) as f:
            f.write(bib_content)
            f.flush()
            path = f.name

        try:
            total, updated, skipped, not_found = ub.update_journal_iso(
                path, dry_run=False, verbose=False
            )
            assert updated == 1

            with open(path) as f:
                result = f.read()
            assert "journal-iso" in result
            assert "Nature" in result  # abbreviation of Nature is "Nature"
        finally:
            os.unlink(path)

    def test_skips_populated_journal_iso(self):
        """Already-set journal-iso should be skipped."""
        bib_content = textwrap.dedent("""\
            @article{Smith2012,
                author      = {Smith, J.},
                title       = {Test},
                journal     = {Nature},
                journal-iso = {Nat.},
                year        = {2012}
            }
        """)
        with tempfile.NamedTemporaryFile(mode="w", suffix=".bib",
                                         delete=False) as f:
            f.write(bib_content)
            f.flush()
            path = f.name

        try:
            total, updated, skipped, not_found = ub.update_journal_iso(
                path, dry_run=False, verbose=False
            )
            assert skipped == 1
            assert updated == 0

            with open(path) as f:
                result = f.read()
            # Should still say "Nat." not overwritten
            assert "Nat.}" in result
        finally:
            os.unlink(path)

    def test_overwrite_mode(self):
        """With overwrite=True, existing values should be replaced."""
        bib_content = textwrap.dedent("""\
            @article{Smith2012,
                author      = {Smith, J.},
                title       = {Test},
                journal     = {Nature},
                journal-iso = {wrong},
                year        = {2012}
            }
        """)
        with tempfile.NamedTemporaryFile(mode="w", suffix=".bib",
                                         delete=False) as f:
            f.write(bib_content)
            f.flush()
            path = f.name

        try:
            total, updated, skipped, not_found = ub.update_journal_iso(
                path, dry_run=False, verbose=False, overwrite=True
            )
            assert updated == 1

            with open(path) as f:
                result = f.read()
            assert "wrong" not in result
        finally:
            os.unlink(path)

    def test_dry_run_no_changes(self):
        """Dry run should not modify the file."""
        bib_content = textwrap.dedent("""\
            @article{Smith2012,
                author      = {Smith, J.},
                title       = {Test},
                journal     = {Molecular Biology and Evolution},
                journal-iso = {},
                year        = {2012}
            }
        """)
        with tempfile.NamedTemporaryFile(mode="w", suffix=".bib",
                                         delete=False) as f:
            f.write(bib_content)
            f.flush()
            path = f.name

        try:
            ub.update_journal_iso(path, dry_run=True, verbose=False)

            with open(path) as f:
                result = f.read()
            # File should be unchanged
            assert result == bib_content
        finally:
            os.unlink(path)

    def test_not_found_journal(self):
        """Unknown journal should be counted as not_found."""
        bib_content = textwrap.dedent("""\
            @article{Smith2012,
                author      = {Smith, J.},
                title       = {Test},
                journal     = {Fake Journal Of Nothing},
                journal-iso = {},
                year        = {2012}
            }
        """)
        with tempfile.NamedTemporaryFile(mode="w", suffix=".bib",
                                         delete=False) as f:
            f.write(bib_content)
            f.flush()
            path = f.name

        try:
            total, updated, skipped, not_found = ub.update_journal_iso(
                path, dry_run=False, verbose=False
            )
            assert not_found == 1
            assert updated == 0
        finally:
            os.unlink(path)

    def test_bibtex_braces_in_journal(self):
        """Journal names with {braces} should match after stripping."""
        bib_content = textwrap.dedent("""\
            @article{Test2012,
                author      = {Smith, J.},
                title       = {Test},
                journal     = {{BMC} Bioinformatics},
                journal-iso = {},
                year        = {2012}
            }
        """)
        with tempfile.NamedTemporaryFile(mode="w", suffix=".bib",
                                         delete=False) as f:
            f.write(bib_content)
            f.flush()
            path = f.name

        try:
            total, updated, skipped, not_found = ub.update_journal_iso(
                path, dry_run=False, verbose=False
            )
            assert updated == 1

            with open(path) as f:
                result = f.read()
            assert "BMC" in result
        finally:
            os.unlink(path)


# ===========================================================================
# Format bibtex entry
# ===========================================================================

class TestFormatBibtexEntry:
    """Tests for format_bibtex_entry()."""

    def test_basic_formatting(self):
        entry = {
            "entry_type": "article",
            "author": "Smith, J. and Jones, K.",
            "title": "A Test Article",
            "journal": "Nature",
            "year": "2012",
            "volume": "42",
            "pages": "1-15",
            "abstract": "An abstract.",
            "doi": "10.1234/test",
        }
        result = ub.format_bibtex_entry(
            entry, "SmithAndJones2012", "test.pdf",
            ub.DEFAULT_REFS
        )
        assert result.startswith("@article{SmithAndJones2012,")
        assert "author" in result
        assert "title" in result
        assert "journal" in result
        assert "journal-iso" in result
        assert "file" in result
        assert "doi" in result

    def test_protected_title(self):
        """Protected words in title should be wrapped in braces."""
        entry = {
            "entry_type": "article",
            "author": "Smith, J.",
            "title": "DNA Replication Mechanisms",
            "journal": "Nature",
            "year": "2012",
        }
        result = ub.format_bibtex_entry(
            entry, "Smith2012", "test.pdf", ub.DEFAULT_REFS
        )
        assert "{DNA}" in result

    def test_journal_iso_auto_populated(self):
        """journal-iso should be auto-populated when not provided."""
        entry = {
            "entry_type": "article",
            "author": "Smith, J.",
            "title": "Test",
            "journal": "Molecular Biology and Evolution",
            "year": "2012",
        }
        result = ub.format_bibtex_entry(
            entry, "Smith2012", "test.pdf", ub.DEFAULT_REFS
        )
        assert "Mol. Biol. Evol." in result


# ===========================================================================
# Sanitize filename
# ===========================================================================

class TestSanitizeFilename:
    """Tests for _sanitize_filename()."""

    def test_spaces_to_periods(self):
        assert "hello.world" in ub._sanitize_filename("hello world")

    def test_colons_to_hyphens(self):
        result = ub._sanitize_filename("title: subtitle")
        assert ":" not in result
        assert "-" in result

    def test_question_marks_removed(self):
        result = ub._sanitize_filename("is.this.real?")
        assert "?" not in result

    def test_multiple_periods_collapsed(self):
        result = ub._sanitize_filename("a...b")
        assert "..." not in result
        assert "a.b" in result

    def test_parentheses_to_periods(self):
        result = ub._sanitize_filename("gene(s)")
        assert "(" not in result
        assert ")" not in result


# ===========================================================================
# End-to-end: process_entry
# ===========================================================================

class TestProcessEntry:
    """Tests for process_entry() end-to-end."""

    def test_basic_entry_processing(self):
        entry = {
            "entry_type": "article",
            "author": "Smith, John and Jones, Karen and Lee, Michael",
            "title": "A Novel Approach to DNA Replication",
            "journal": "Nature",
            "year": "2012",
            "volume": "42",
            "pages": "1-15",
        }
        bibtex, key, filename = ub.process_entry(
            entry, refs_dir=ub.DEFAULT_REFS, verbose=False
        )
        assert key == "SmithEtAl2012"
        assert filename.startswith("Smith.et.al_2012_")
        assert "DNA" in filename
        assert filename.endswith(".pdf")
        assert bibtex.startswith("@article{SmithEtAl2012,")

    def test_two_author_entry(self):
        entry = {
            "entry_type": "article",
            "author": "Garcia, A. and Lopez, B.",
            "title": "Simple Title",
            "journal": "Science",
            "year": "2020",
        }
        bibtex, key, filename = ub.process_entry(
            entry, refs_dir=ub.DEFAULT_REFS, verbose=False
        )
        assert key == "GarciaAndLopez2020"
        assert "Garcia.and.Lopez" in filename


# ===========================================================================
# Protected words list
# ===========================================================================

class TestProtectedWords:
    """Tests that the PROTECTED_WORDS list is comprehensive."""

    @pytest.mark.parametrize("word", [
        "DNA", "RNA", "mRNA", "tRNA", "rRNA",
        "CRISPR", "ATP", "HIV", "SARS",
        "PCR", "ANOVA", "AIC",
    ])
    def test_word_in_protected_list(self, word):
        assert word in ub._PROTECTED_SET

    @pytest.mark.parametrize("word", [
        "DNA", "RNA", "mRNA", "CRISPR",
    ])
    def test_protected_in_filename(self, word):
        """Protected words should survive filename title cleaning."""
        result = ub._clean_title_for_filename(f"Analysis of {word} Levels")
        assert word in result


# ===========================================================================
# RIS parsing (if rispy available)
# ===========================================================================

class TestRISParsing:
    """Tests for RIS file parsing."""

    @pytest.mark.skipif(not ub.HAS_RISPY, reason="rispy not installed")
    def test_parse_ris_file(self):
        ris_content = textwrap.dedent("""\
            TY  - JOUR
            AU  - Smith, John
            AU  - Jones, Karen
            TI  - A Test Article
            JO  - Nature
            PY  - 2012
            VL  - 42
            SP  - 1
            EP  - 15
            DO  - 10.1234/test
            ER  -
        """)
        with tempfile.NamedTemporaryFile(mode="w", suffix=".ris",
                                         delete=False) as f:
            f.write(ris_content)
            f.flush()
            path = f.name

        try:
            entries = ub.parse_ris_file(path)
            assert len(entries) == 1
            e = entries[0]
            assert "Smith" in e["author"]
            assert "Jones" in e["author"]
            assert e["year"] == "2012"
        finally:
            os.unlink(path)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
