#!/usr/bin/env bash
# =============================================================================
# File: add_page_numbers.sh
# Date: 2025-11-10
# Version: 1.1.0
# Purpose: Add centered page numbers to the top margin of each page in a PDF.
# Usage:   add_page_numbers.sh [options] FILE.pdf
#
# Options:
#   -n, --dry-run    Show commands but do not execute them.
#   -v, --verbose    Print detailed progress information.
#
# Input:
#   A single PDF file.
#
# Output:
#   A new PDF named <FILE>-numbered.pdf with page numbers added.
#
# Chat name: add_page_numbers
# GPT Model: GPT-5
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT
# =============================================================================

DRYRUN=false
VERBOSE=false

log() {
    if $VERBOSE; then
        printf '[INFO] %s\n' "$*"
    fi
}

run() {
    if $DRYRUN; then
        printf '[DRYRUN] %s\n' "$*"
    else
        eval "$@"
    fi
}

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--dry-run) DRYRUN=true; shift ;;
    -v|--verbose) VERBOSE=true; shift ;;
    -h|--help)
        grep '^# ' "$0" | sed 's/^# //'
        exit 0
        ;;
    -*)
        echo "Unknown option: $1" >&2
        exit 1
        ;;
    *)
        FILE="$1"
        shift
        ;;
  esac
done

# ---------------------------------------------------------------------------
# Check input
# ---------------------------------------------------------------------------
if [[ -z "${FILE:-}" ]]; then
    echo "Error: Must supply a PDF file."
    echo "Usage: add_page_numbers.sh [options] FILE.pdf"
    exit 1
fi

if [[ ! -f "$FILE" ]]; then
    echo "Error: File not found: $FILE"
    exit 1
fi

BASENAME=$(basename "$FILE")
TMPSTAMP="stamp-$$.pdf"
OUTFILE="${FILE/.pdf/-numbered.pdf}"

log "Input: $FILE"
log "Output: $OUTFILE"

# ---------------------------------------------------------------------------
# Determine number of pages
# ---------------------------------------------------------------------------
PAGECOUNT=$(pdftk "$FILE" dump_data | grep -i "^NumberOfPages" | awk '{print $2}')

if [[ -z "$PAGECOUNT" ]]; then
    echo "Error: Could not determine number of pages." >&2
    exit 1
fi

log "Pages detected: $PAGECOUNT"

# ---------------------------------------------------------------------------
# Create stamp PDF containing sequential page numbers
# ---------------------------------------------------------------------------
# Enscripter generates one page per line, so we emit PAGECOUNT blank lines.
# Footer formats number centered:  --footer '|$%|'
run "enscript -F Times-Roman10 --fancy-header=fancy -L1 -b '||' --footer '|$%|' -o- < <(for i in \$(seq 1 $PAGECOUNT); do echo; done) | ps2pdf - \"$TMPSTAMP\""

# ---------------------------------------------------------------------------
# Apply page number stamp to PDF
# ---------------------------------------------------------------------------
run "pdftk \"$FILE\" multistamp \"$TMPSTAMP\" output \"$OUTFILE\""

# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------
run "rm -f \"$TMPSTAMP\""

log "Done."
echo "Created: $OUTFILE"
