#!/bin/sh
#-------------------------------------------------------------------------------
# Created by mikeg 09/19/19 from ris2bib script in cb2Bib tools
# bib2isi  --  Script to convert BibTeX to ISI format
# cb2Bib Tools
#
# Copyright (C) 2005-2017 by Pere Constans
# constans@molspaces.com
#
# Improvements and modifications:
# Copyright (C) 2009 by Filippo Rusconi
# rusconi@mnhn.fr
#
# May/June 2009:
# - Added checks to ensure that the used commands are available on
#   system.
# - Make use of mktemp to create a temp directory.
#
# See LICENSE file that comes with this distribution
#
# Usage: bib2isi input_bib output_isi
#-------------------------------------------------------------------------------
# Using ris2xml and xml2isi utilities from:
# http://bibutils.refbase.org/
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Init variables
#-------------------------------------------------------------------------------
# Modify accordingly
#ris2xml=/usr/local/bin/ris2xml
#xml2bib=/usr/local/bin/xml2bib
bib2xml=bib2xml #only changed here
xml2isi=xml2isi
bib2xml_flags="-u" # use unicode characters - default
xml2isi_flags="-nb" #-nb = no byte order mark (bom). might want to use '-o unicode' 
#-------------------------------------------------------------------------------

# Immediately check that the needed programs are there:
"${bib2xml}" --version > /dev/null 2>&1

if [ "$?" != "0" ]
then
    echo "Program bib2xml (suite bibutils) is required."
    echo "Set it in your path, and/or modify $0 accordingly."
    echo "Ending processing."
    exit 1
fi

"${xml2isi}" --version > /dev/null 2>&1

if [ "$?" != "0" ]
then
    echo "Program xml2isi (suite bibutils) is required."
    echo "Set it in your path, and/or modify $0 accordingly."
    echo "Ending processing."
    exit 1
fi

# Make sure we trap errors (we put that after the tests above because
# we need the tests to fail, in case, without exiting immediately).
set -e

# Getting filenames from command line
echo "cb2Bib Tools: Script to convert RIS format to BibTeX"
echo ""
echo "It uses external package bibutils from"
echo "http://bibutils.refbase.org/"
echo ""
if test "$#" != 2; then
    cat <<EOF
Usage: $0 input_bib output_isi
EOF
    exit 2
fi

# Create temporary directory
# Note that we use the mktemp utility that ensures that
# we do not overwrite any preexisting directory
tmp_dir=$(mktemp -d c2b_tools_tmp.XXXXXXXX) || exit 1

# Setting files
bib="$1"
isi="$2"
work_dir="$PWD"

# Preparing temporary files
cp "$bib" "${tmp_dir}"/c2b_tmp.bib
#cp "$isi" "${tmp_dir}"/c2b_tmp.isi

# isiutils procedure
cd "${tmp_dir}"
"${bib2xml}" "${bib2xml_flags}" c2b_tmp.bib | "${xml2isi}" "${xml2isi_flags}" | sed 's%^ISSUE=%NUMBER=%g' > c2b_tmp.isi

# Clean up
cd "${work_dir}"
cp "${tmp_dir}"/c2b_tmp.isi "$isi"
rm -rf "${tmp_dir}"
echo ""
echo "$0 ended."
