#!/home/mikeg/.venv/daily/bin/python3
# ============================================================================
# Script:       bibtex.tools.mcp.py
# Version:      1.0.0
# Date:         2026-04-28
# Purpose:      MCP server exposing paper acquisition tools to Claude Code
#
# Tools exposed:
#   resolve_doi(doi)               -- Crossref API -> metadata dict
#   resolve_pmid(pmid)             -- NCBI eutils -> metadata dict
#   search_bibliography(query)     -- search master bib by title/author/DOI/PMID
#   generate_bib_entry(metadata)   -- key + filename + formatted BibTeX
#   fetch_pdf(url, output_path, use_proxy) -- browser window download
#   add_to_bibliography(bib_text)  -- prepend to master bib with backup
#   create_symlink(target, link_dir) -- symlink PDF into a project directory
#
# Usage:        Configured in ~/.claude/settings.json mcpServers block.
#               Not intended to be run directly.
# Input:        JSON-RPC over stdio (MCP protocol)
# Output:       JSON-RPC over stdio
#
# Requirements:
#   /home/mikeg/.venv/daily (mcp installed)
#   /usr/bin/python3 with python3-gi + gir1.2-webkit2-4.1 (for fetch_pdf)
#
# Session:      BibTeX Tools - Browser PDF Fetch
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               Claude Sonnet 4.6
# ============================================================================

import importlib.util
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from urllib.error import URLError
from urllib.request import Request, urlopen

from mcp.server.fastmcp import FastMCP

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR   = Path(__file__).parent
REFS_DIR     = Path.home() / "References"
MASTER_BIB   = Path.home() / "BiBTeX" / "bibliography.full.bib"
BROWSER_SCRIPT = SCRIPT_DIR / "fetch.pdf.with.browser.py"
UTK_PROXY    = "https://utk.idm.oclc.org/login?url="

# ---------------------------------------------------------------------------
# Import reusable functions from update.bib.py
# ---------------------------------------------------------------------------
_spec = importlib.util.spec_from_file_location(
    "update_bib", SCRIPT_DIR / "update.bib.py"
)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)

parse_authors       = _mod.parse_authors
generate_key        = _mod.generate_key
generate_filename   = _mod.generate_filename
format_bibtex_entry = _mod.format_bibtex_entry
backup_and_prepend  = _mod.backup_and_prepend
parse_bibtex_string = _mod.parse_bibtex_string

# ---------------------------------------------------------------------------
# MCP server
# ---------------------------------------------------------------------------
mcp = FastMCP("bibtex-tools")


# ---------------------------------------------------------------------------
# Metadata helpers
# ---------------------------------------------------------------------------

def _crossref_authors_to_bibtex(author_list):
    """Convert Crossref author list to BibTeX 'and'-separated string."""
    parts = []
    for a in author_list:
        family = a.get("family", "")
        given  = a.get("given", "")
        if family and given:
            parts.append(f"{family}, {given}")
        elif family:
            parts.append(family)
    return " and ".join(parts)


def _ncbi_author_to_bibtex(name_str):
    """Convert NCBI author name 'Gold ER' -> 'Gold, E. R.'"""
    parts = name_str.strip().split()
    if len(parts) >= 2:
        family   = parts[0]
        initials = ". ".join(list(parts[1])) + "."
        return f"{family}, {initials}"
    return name_str


def _strip_jats(text):
    """Strip JATS/XML tags from Crossref abstract."""
    return re.sub(r"<[^>]+>", "", text or "").strip()


def _fetch_json(url, headers=None):
    """GET a URL and return parsed JSON, or raise on error."""
    req = Request(url, headers=headers or {})
    with urlopen(req, timeout=10) as resp:
        return json.loads(resp.read().decode())


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------

@mcp.tool()
def resolve_doi(doi: str) -> dict:
    """Fetch citation metadata for a paper by DOI using the Crossref API.

    Returns a metadata dict with: author, title, journal, year, volume,
    pages, abstract, doi, pmid (if available), entry_type.
    """
    doi = doi.strip().lstrip("https://doi.org/").lstrip("doi:")
    url = f"https://api.crossref.org/works/{doi}"
    try:
        data = _fetch_json(url, headers={"User-Agent": "BibTeXTools/1.0 (mailto:mikeg@utk.edu)"})
    except URLError as e:
        return {"error": f"Crossref request failed: {e}"}

    msg = data.get("message", {})

    title_list = msg.get("title", [])
    title = title_list[0] if title_list else ""

    journal_list = msg.get("container-title", [])
    journal = journal_list[0] if journal_list else ""

    date_parts = msg.get("published", msg.get("published-print", {})).get("date-parts", [[]])
    year = str(date_parts[0][0]) if date_parts and date_parts[0] else ""

    authors_raw = msg.get("author", [])
    author_str  = _crossref_authors_to_bibtex(authors_raw)

    abstract = _strip_jats(msg.get("abstract", ""))

    # PMID sometimes in external-ids
    pmid = ""
    for id_obj in msg.get("assertion", []):
        if id_obj.get("name") == "pmid":
            pmid = id_obj.get("value", "")

    return {
        "author":     author_str,
        "title":      title,
        "journal":    journal,
        "year":       year,
        "volume":     str(msg.get("volume", "")),
        "pages":      str(msg.get("page", "")),
        "abstract":   abstract,
        "doi":        doi,
        "pmid":       pmid,
        "entry_type": "article",
    }


@mcp.tool()
def resolve_pmid(pmid: str) -> dict:
    """Fetch citation metadata for a paper by PubMed ID using NCBI eutils.

    Returns the same metadata dict structure as resolve_doi.
    """
    pmid = pmid.strip()
    url  = (
        "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"
        f"?db=pubmed&id={pmid}&retmode=json"
    )
    try:
        data = _fetch_json(url)
    except URLError as e:
        return {"error": f"NCBI request failed: {e}"}

    result = data.get("result", {}).get(pmid, {})
    if not result:
        return {"error": f"No result for PMID {pmid}"}

    authors_raw = result.get("authors", [])
    author_str  = " and ".join(
        _ncbi_author_to_bibtex(a["name"]) for a in authors_raw if a.get("authtype") == "Author"
    )

    # Year from pubdate "2025 Mar 25" or "2025"
    pubdate = result.get("pubdate", "")
    year    = pubdate.split()[0] if pubdate else ""

    # DOI from articleids
    doi = ""
    for id_obj in result.get("articleids", []):
        if id_obj.get("idtype") == "doi":
            doi = id_obj.get("value", "")
            break

    return {
        "author":     author_str,
        "title":      result.get("title", "").rstrip("."),
        "journal":    result.get("fulljournalname", result.get("source", "")),
        "year":       year,
        "volume":     result.get("volume", ""),
        "pages":      result.get("pages", ""),
        "abstract":   "",  # not in esummary; would need efetch
        "doi":        doi,
        "pmid":       pmid,
        "entry_type": "article",
    }


@mcp.tool()
def search_bibliography(query: str) -> list:
    """Search the master bibliography for entries matching a query string.

    Matches against title, author surnames, DOI, and PMID (case-insensitive).
    Returns up to 10 matching entries, each with: cite_key, author, title,
    journal, year, doi, pmid, file.
    """
    if not MASTER_BIB.exists():
        return [{"error": f"Master bib not found: {MASTER_BIB}"}]

    text    = MASTER_BIB.read_text(errors="replace")
    entries = parse_bibtex_string(text)
    q       = query.lower()

    results = []
    for e in entries:
        haystack = " ".join([
            e.get("title",   ""),
            e.get("author",  ""),
            e.get("doi",     ""),
            e.get("pmid",    ""),
            e.get("cite_key",""),
        ]).lower()
        if q in haystack:
            results.append({
                "cite_key": e.get("cite_key", ""),
                "author":   e.get("author",   ""),
                "title":    e.get("title",    ""),
                "journal":  e.get("journal",  ""),
                "year":     e.get("year",     ""),
                "doi":      e.get("doi",      ""),
                "pmid":     e.get("pmid",     ""),
                "file":     e.get("file",     ""),
            })
            if len(results) >= 10:
                break

    return results


@mcp.tool()
def generate_bib_entry(metadata: dict) -> dict:
    """Generate a BibTeX entry from a metadata dict.

    Uses the same citation key and filename conventions as update.bib.py.
    Input metadata dict should include: author, title, journal, year, and
    optionally volume, pages, abstract, doi, pmid, entry_type.

    Returns: {bib_text, cite_key, pdf_filename, pdf_path}.
    """
    author_str = metadata.get("author", "")
    year       = str(metadata.get("year", ""))
    title      = metadata.get("title",   "")
    journal    = metadata.get("journal", "")

    authors      = parse_authors(author_str)
    cite_key     = generate_key(authors, year)
    pdf_filename = generate_filename(authors, year, title, journal)
    pdf_path     = str(REFS_DIR / pdf_filename)

    # Build entry dict in update.bib.py's expected shape
    entry = {
        "entry_type": metadata.get("entry_type", "article"),
        "author":     author_str,
        "title":      title,
        "journal":    journal,
        "year":       year,
        "volume":     metadata.get("volume",   ""),
        "pages":      metadata.get("pages",    ""),
        "abstract":   metadata.get("abstract", ""),
        "doi":        metadata.get("doi",      ""),
        "pmid":       metadata.get("pmid",     ""),
    }

    bib_text = format_bibtex_entry(entry, cite_key, pdf_filename, REFS_DIR)

    return {
        "bib_text":     bib_text,
        "cite_key":     cite_key,
        "pdf_filename": pdf_filename,
        "pdf_path":     pdf_path,
    }


@mcp.tool()
def fetch_pdf(url: str, output_path: str, use_proxy: bool = False) -> dict:
    """Open a mini browser window to download a PDF via university access.

    Blocks until the user downloads the file or cancels/times out.
    On campus, use_proxy=False. Off campus, use_proxy=True to route through
    the UTK proxy (https://utk.idm.oclc.org/login?url=).

    Returns: {success, output_path, message}.
    """
    if not BROWSER_SCRIPT.exists():
        return {"success": False, "message": f"Browser script not found: {BROWSER_SCRIPT}"}

    cmd = ["/usr/bin/python3", str(BROWSER_SCRIPT), url, output_path]
    if use_proxy:
        cmd += ["--proxy-prefix", UTK_PROXY]

    result = subprocess.run(cmd)
    success = result.returncode == 0 and Path(output_path).is_file()

    return {
        "success":     success,
        "output_path": output_path if success else "",
        "message":     "Downloaded successfully." if success else "Download cancelled or failed.",
    }


@mcp.tool()
def add_to_bibliography(bib_text: str, dry_run: bool = False) -> dict:
    """Prepend a BibTeX entry to the master bibliography file.

    Uses the standard backup chain:
      Bkups/bibliography.full.bib -> Bkups/bibliography.full.bkup
      bibliography.full.bib       -> Bkups/bibliography.full.bib
      new entry + old bib         -> bibliography.full.bib

    Returns: {success, message, bib_path}.
    """
    if not MASTER_BIB.exists():
        return {"success": False, "message": f"Master bib not found: {MASTER_BIB}"}

    try:
        backup_and_prepend(bib_text, MASTER_BIB, dry_run=dry_run, verbose=False)
        msg = f"[dry-run] Would prepend to {MASTER_BIB}" if dry_run else f"Prepended to {MASTER_BIB}"
        return {"success": True, "message": msg, "bib_path": str(MASTER_BIB)}
    except Exception as e:
        return {"success": False, "message": str(e)}


@mcp.tool()
def create_symlink(target: str, link_dir: str) -> dict:
    """Create a symlink to a PDF in the specified directory.

    Args:
        target:   Absolute path to the PDF (e.g. ~/References/Author_Year_title.pdf)
        link_dir: Directory where the symlink should be created

    Returns: {success, link_path, message}.
    """
    target_path  = Path(target).expanduser().resolve()
    link_dir_path = Path(link_dir).expanduser().resolve()

    if not target_path.exists():
        return {"success": False, "message": f"Target not found: {target_path}"}

    link_dir_path.mkdir(parents=True, exist_ok=True)
    link_path = link_dir_path / target_path.name

    if link_path.exists() or link_path.is_symlink():
        return {"success": True, "link_path": str(link_path),
                "message": "Symlink already exists."}

    link_path.symlink_to(target_path)
    return {"success": True, "link_path": str(link_path),
            "message": f"Symlinked {link_path} -> {target_path}"}


# ---------------------------------------------------------------------------
if __name__ == "__main__":
    mcp.run()
