#!/bin/bash

# ============================================================================
# Purpose:     Bundle a .tex file, its figures, matching .key.tex file (as a
#              symlink), and any compiled PDFs into a .tar.gz archive.
# Usage:       ./bundle_tex_figures.sh [-n] [-v 0|1] <file.tex>
# Input:       A .tex file with \includegraphics{} commands and optional .key.tex
# Output:      A .tar.gz archive with organized contents.
# Date:        2025-05-02
# Version:     2.2
# Chat name:   Bishop Bash
# GPT Model:   GPT-4
# Generated by Michael Gilchrist in collaboration with ChatGPT
# ============================================================================

set -e

DRY_RUN=0
VERBOSE=1

# Supported LaTeX image extensions
EXTENSIONS=(.png .pdf .jpg .jpeg .eps)

# Verbose logging function
log() {
    if [ "$VERBOSE" -eq 1 ]; then
        echo "$@"
    fi
}

# Parse options
while getopts ":nv:" opt; do
    case $opt in
        n) DRY_RUN=1 ;;
        v) VERBOSE=$OPTARG ;;
        \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
        :) echo "Option -$OPTARG requires an argument." >&2; exit 1 ;;
    esac
done

shift $((OPTIND -1))

if [ $# -ne 1 ]; then
    echo "Usage: $0 [-n] [-v 0|1] <file.tex>"
    exit 1
fi

TEXFILE="$1"
[ ! -f "$TEXFILE" ] && echo "Error: File '$TEXFILE' not found." && exit 1

TEX_BASENAME=$(basename "$TEXFILE" .tex)
KEYFILE="${TEX_BASENAME}.key.tex"
ARCHIVE_NAME="${TEX_BASENAME}_bundle.tar.gz"
TMPDIR=$(mktemp -d)

log "Processing: $TEXFILE"
log "Temporary build directory: $TMPDIR"

# Extract active lines before \end{document}
log "Scanning for \includegraphics{} entries..."
LINES=$(awk '/^[^%]*\\end{document}/ { exit } { print }' "$TEXFILE")

GRAPHICS_FILES=$(echo "$LINES" | grep -oP '\\includegraphics(?:\[[^\]]*\])?\{[^}]+\}' | \
    sed -E 's/.*\{([^}]+)\}.*/\1/')

mkdir -p "$TMPDIR/Figures"
declare -a INCLUDED_FILES

resolve_graphic() {
    local base="$1"
    if [[ "$base" == *.* ]]; then
        [ -f "$base" ] && echo "$base" && return 0
    else
        for ext in "${EXTENSIONS[@]}"; do
            if [ -f "$base$ext" ]; then
                echo "$base$ext"
                return 0
            fi
        done
    fi
    return 1
}

log "Resolving and copying figure files..."
for GRAPHIC in $GRAPHICS_FILES; do
    FILE=$(resolve_graphic "$GRAPHIC")
    if [ -n "$FILE" ]; then
        TARGET=$(readlink -f "$FILE")
        BASENAME_IMG=$(basename "$TARGET")
        INCLUDED_FILES+=("Figures/$BASENAME_IMG")
        if [ "$DRY_RUN" -eq 0 ]; then
            cp "$TARGET" "$TMPDIR/Figures/"
        fi
        log "  Included: $GRAPHIC -> Figures/$BASENAME_IMG"
    else
        echo "Warning: Graphic '$GRAPHIC' not found with any known extension."
    fi
done

log "Copying main .tex file..."
cp "$TEXFILE" "$TMPDIR/"
INCLUDED_FILES+=("$(basename "$TEXFILE")")

if [ -f "$KEYFILE" ]; then
    log "Linking .key.tex file: $KEYFILE"
    ln -s "$(realpath --relative-to="$TMPDIR" "$KEYFILE")" "$TMPDIR/$(basename "$KEYFILE")"
    INCLUDED_FILES+=("$(basename "$KEYFILE")")
fi

log "Checking for compiled PDFs..."
for SRC in "$TEXFILE" "$KEYFILE"; do
    PDF="${SRC%.tex}.pdf"
    if [ -f "$PDF" ]; then
        cp "$PDF" "$TMPDIR/"
        INCLUDED_FILES+=("$(basename "$PDF")")
        log "  Included PDF: $PDF"
    fi
done

if [ "$DRY_RUN" -eq 1 ]; then
    echo "Dry Run: Would include the following in $ARCHIVE_NAME:"
    for FILE in "${INCLUDED_FILES[@]}"; do
        echo "  $FILE"
    done
else
    log "Creating archive: $ARCHIVE_NAME"
    tar -czf "$ARCHIVE_NAME" -C "$TMPDIR" .
    echo "Archive created: $ARCHIVE_NAME"
    rm -rf "$TMPDIR"
fi
