#!/bin/bash

# Purpose: Download PDFs using DOI numbers. First, it checks for an open-access PDF using the Unpaywall API.
#          If not found, it resolves the DOI via doi.org and attempts to extract a direct PDF link from the HTML,
#          assuming the user has full access to the journal content. Optionally uses a cookies file for authentication.
# Input: 1) A text file with one DOI per line.
#        2) (Optional) A cookies.txt file to use for authenticated requests.
# Output: PDF files saved to a folder called `downloaded_pdfs/`
# Date: 2025-04-03
# Version: 2.1
# Chat name: Bishop Bash
# GPT Model: GPT-4
# Author: Generated by Michael Gilchrist in collaboration with ChatGPT

# ---------------------------
# Handle input arguments
# ---------------------------
DOI_FILE="$1"
COOKIES_FILE="$2"
DOWNLOAD_DIR="downloaded_pdfs"
EMAIL="your-email@example.com"  # 🔁 Replace with your actual email for Unpaywall

# Check for DOI file
if [ -z "$DOI_FILE" ] || [ ! -f "$DOI_FILE" ]; then
  echo "❌ Error: You must provide a valid DOI file."
  echo "Usage: $0 path/to/dois.txt [cookies.txt]"
  exit 1
fi

# Check for required tools
for tool in curl jq grep sed; do
  if ! command -v $tool &>/dev/null; then
    echo "❌ Error: $tool is not installed."
    exit 1
  fi
done

mkdir -p "$DOWNLOAD_DIR"

# ---------------------------
# Function: extract PDF URL from HTML
# ---------------------------
extract_pdf_from_html() {
  local url="$1"
  local html

  if [ -n "$COOKIES_FILE" ] && [ -f "$COOKIES_FILE" ]; then
    html=$(curl -s -L -A "Mozilla/5.0" --cookie "$COOKIES_FILE" "$url")
  else
    html=$(curl -s -L -A "Mozilla/5.0" "$url")
  fi

  echo "$html" | grep -Eo 'https?://[^"'\'' >]+\.pdf' | head -n 1
}

# ---------------------------
# Main loop: process each DOI
# ---------------------------
while IFS= read -r DOI || [ -n "$DOI" ]; do
  [ -z "$DOI" ] && continue  # Skip empty lines
  echo "🔍 Processing DOI: $DOI"

  # Step 1: Try Unpaywall
  RESPONSE=$(curl -s "https://api.unpaywall.org/v2/$DOI?email=$EMAIL")
  PDF_URL=$(echo "$RESPONSE" | jq -r '.best_oa_location.url_for_pdf')

  if [ "$PDF_URL" != "null" ] && [ -n "$PDF_URL" ]; then
    echo "✅ Found OA PDF via Unpaywall."
  else
    echo "⚠️  No OA PDF. Trying DOI resolution..."
    RESOLVED_URL=$(curl -s -I -L "https://doi.org/$DOI" | grep -i '^location:' | tail -n 1 | sed 's/location:[[:space:]]*//I' | tr -d '\r')

    if [ -n "$RESOLVED_URL" ]; then
      PDF_URL=$(extract_pdf_from_html "$RESOLVED_URL")
      if [ -n "$PDF_URL" ]; then
        echo "✅ Found PDF link on publisher page."
      else
        echo "❌ No PDF link found on publisher page."
      fi
    else
      echo "❌ Could not resolve DOI."
    fi
  fi

  # Step 3: Download the PDF
  if [ -n "$PDF_URL" ]; then
    FILENAME=$(echo "$DOI" | sed 's|/|_|g').pdf
    echo "⬇️  Downloading: $FILENAME"

    if [ -n "$COOKIES_FILE" ] && [ -f "$COOKIES_FILE" ]; then
      curl -L -A "Mozilla/5.0" --cookie "$COOKIES_FILE" "$PDF_URL" -o "$DOWNLOAD_DIR/$FILENAME"
    else
      curl -L -A "Mozilla/5.0" "$PDF_URL" -o "$DOWNLOAD_DIR/$FILENAME"
    fi

    if [ $? -eq 0 ]; then
      echo "✅ Download successful."
    else
      echo "❌ Download failed."
    fi
  else
    echo "⚠️  No PDF URL available."
  fi

  echo "-----------------------------------"

done < "$DOI_FILE"
