#!/bin/bash

# Purpose: Extract DOI values from a BibTeX-style file and save them to a plain text file.
# Input: A `.bib` or `.txt` file containing lines like `doi = {...}`
# Output: A text file called `dois.txt` with one DOI per line.
# Date: 2025-04-03
# Version: 1.0
# Chat name: Bishop Bash
# GPT Model: GPT-4
# Author: Generated by Michael Gilchrist in collaboration with ChatGPT

# Usage check
if [ -z "$1" ]; then
  echo "Usage: $0 yourfile.bib"
  exit 1
fi

BIBFILE="$1"
OUTPUT_FILE="dois.txt"

# Extract DOI lines and clean them up
grep -i 'doi[[:space:]]*=' "$BIBFILE" | \
  sed -E 's/.*doi[[:space:]]*=[[:space:]]*[{"]([^}"]+)[}"].*/\1/' \
  > "$OUTPUT_FILE"

echo "✅ DOIs extracted to $OUTPUT_FILE"
