#!/usr/bin/python3
# ============================================================================
# Script:       fetch.pdf.with.browser.py
# Version:      1.0.0
# Date:         2026-04-28
# Purpose:      Mini WebKit2GTK browser for downloading PDFs via university access
#
# Opens a small browser window at the given URL. Intercepts PDF downloads
# and saves them to the specified target path. Exits 0 on success, 1 on
# failure, cancel, or timeout.
#
# Usage:        fetch.pdf.with.browser.py URL TARGET_PATH [OPTIONS]
# Input:        URL         -- starting URL to load
#               TARGET_PATH -- absolute path where the PDF should be saved
# Output:       Saved PDF at TARGET_PATH; exit 0 on success, 1 on failure
#
# Options:
#   --proxy-prefix URL   Prepend proxy URL to the initial URL
#                        (e.g. https://utk.idm.oclc.org/login?url=)
#   --timeout SECS       Auto-close after N seconds (0 = no timeout, default 120)
#   -h, --help           Show this help message
#
# Requirements:
#   /usr/bin/python3 (system Python, NOT venv)
#   python3-gi, gir1.2-webkit2-4.1, gir1.2-gtk-3.0
#
# Session:      BibTeX Tools - Browser PDF Fetch
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               Claude Sonnet 4.6
# ============================================================================

import argparse
import os
import sys

import gi
gi.require_version('WebKit2', '4.1')
gi.require_version('Gtk', '3.0')
from gi.repository import GLib, Gtk, WebKit2


def parse_args():
    p = argparse.ArgumentParser(
        description='Mini browser: download a PDF via university library access'
    )
    p.add_argument('url', help='Starting URL to load')
    p.add_argument('target_path', help='Absolute path where the PDF will be saved')
    p.add_argument('--proxy-prefix', default='',
                   help='Prepend proxy URL (e.g. https://utk.idm.oclc.org/login?url=)')
    p.add_argument('--timeout', type=int, default=120,
                   help='Auto-cancel after N seconds (0 = no timeout, default 120)')
    return p.parse_args()


def main():
    args = parse_args()

    target_path = os.path.abspath(args.target_path)
    url = (args.proxy_prefix + args.url) if args.proxy_prefix else args.url
    basename = os.path.basename(target_path)

    download_success = [False]

    # --- Build UI ---
    window = Gtk.Window(title=f'Fetch PDF: {basename}')
    window.set_default_size(1100, 800)

    vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=0)
    window.add(vbox)

    # Address bar
    hbox_nav = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=4)
    hbox_nav.set_margin_start(4)
    hbox_nav.set_margin_end(4)
    hbox_nav.set_margin_top(4)
    hbox_nav.set_margin_bottom(4)

    url_entry = Gtk.Entry()
    url_entry.set_text(url)
    url_entry.set_hexpand(True)
    go_button = Gtk.Button(label='Go')

    hbox_nav.pack_start(url_entry, True, True, 0)
    hbox_nav.pack_start(go_button, False, False, 0)
    vbox.pack_start(hbox_nav, False, False, 0)

    # WebView
    webview = WebKit2.WebView()
    scroll = Gtk.ScrolledWindow()
    scroll.set_hexpand(True)
    scroll.set_vexpand(True)
    scroll.add(webview)
    vbox.pack_start(scroll, True, True, 0)

    # Status / cancel row
    hbox_status = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=8)
    hbox_status.set_margin_start(4)
    hbox_status.set_margin_end(4)
    hbox_status.set_margin_top(2)
    hbox_status.set_margin_bottom(4)

    status_label = Gtk.Label(
        label='Navigate to the paper and click the PDF download link.'
    )
    status_label.set_xalign(0.0)
    status_label.set_hexpand(True)

    cancel_button = Gtk.Button(label='Cancel')
    hbox_status.pack_start(status_label, True, True, 0)
    hbox_status.pack_start(cancel_button, False, False, 0)
    vbox.pack_start(hbox_status, False, False, 0)

    # --- Helpers ---
    def set_status(msg):
        GLib.idle_add(status_label.set_text, msg)

    def quit_with(success):
        download_success[0] = success
        Gtk.main_quit()

    # --- Signal handlers ---
    def on_go_clicked(btn):
        webview.load_uri(url_entry.get_text().strip())

    def on_entry_activate(entry):
        webview.load_uri(entry.get_text().strip())

    def on_load_changed(wv, event):
        if event in (WebKit2.LoadEvent.COMMITTED, WebKit2.LoadEvent.FINISHED):
            current = wv.get_uri() or ''
            GLib.idle_add(url_entry.set_text, current)

    def on_decide_policy(wv, decision, dtype):
        # Force download for PDF responses (and anything WebKit can't display)
        if dtype == WebKit2.PolicyDecisionType.RESPONSE:
            response = decision.get_response()
            mime = response.get_mime_type() if response else ''
            if mime == 'application/pdf' or not decision.is_mime_type_supported():
                decision.download()
                return True
        decision.use()
        return False

    def on_download_started(ctx, download):
        set_status('Download started -- saving...')
        download.connect('decide-destination', on_decide_destination)
        download.connect('received-data', on_received_data)
        download.connect('finished', on_download_finished)
        download.connect('failed', on_download_failed)

    def on_decide_destination(dl, suggested_filename):
        # Redirect to our target path; returning True suppresses the file picker
        dl.set_destination(GLib.filename_to_uri(target_path, None))
        return True

    def on_received_data(dl, data_length):
        received = dl.get_received_data_length()
        prog = dl.get_estimated_progress()
        if prog > 0:
            set_status(
                f'Downloading... {received // 1024} KB ({prog * 100:.0f}%)'
            )
        else:
            set_status(f'Downloading... {received // 1024} KB')

    def on_download_finished(dl):
        if os.path.isfile(target_path) and os.path.getsize(target_path) > 0:
            set_status(f'Done -- saved to {target_path}')
            GLib.timeout_add(1500, lambda: (quit_with(True), False)[1])
        else:
            set_status('Download finished but file not found at expected path.')

    def on_download_failed(dl, error):
        set_status(f'Download failed: {error.message}')

    def on_cancel(btn):
        quit_with(False)

    def on_destroy(win):
        quit_with(False)

    def on_timeout():
        if not download_success[0]:
            set_status('Timed out -- closing window.')
            GLib.timeout_add(800, lambda: (quit_with(False), False)[1])
        return False  # don't repeat

    # --- Wire up signals ---
    go_button.connect('clicked', on_go_clicked)
    url_entry.connect('activate', on_entry_activate)
    webview.connect('load-changed', on_load_changed)
    webview.connect('decide-policy', on_decide_policy)
    cancel_button.connect('clicked', on_cancel)
    window.connect('destroy', on_destroy)

    ctx = webview.get_context()
    ctx.connect('download-started', on_download_started)

    if args.timeout > 0:
        GLib.timeout_add_seconds(args.timeout, on_timeout)

    # --- Launch ---
    webview.load_uri(url)
    window.show_all()
    Gtk.main()

    sys.exit(0 if download_success[0] else 1)


if __name__ == '__main__':
    main()
