#!/bin/bash
# ============================================================================
# Script:       get.pdf.from.bib.pmid.sh
# Version:      2.0.0
# Date:         2026-04-28
# Purpose:      Download PDFs for BibTeX entries using PMIDs
#
# For each entry in BIBFILE that has a pmid and file field, tries to fetch
# the PDF automatically via Pubmed-Batch-Download (open-access only), then
# optionally falls back to a mini browser window for paywalled articles.
# Downloaded files are placed in TARGETDIR with a symlink in the current dir.
# Failed entries are logged to unfetched_pmids.tsv.
#
# Usage:        get.pdf.from.bib.pmid.sh [OPTIONS] BIBFILE TARGETDIR
#               get.pdf.from.bib.pmid.sh BIBFILE TARGETDIR [OPTIONS]
# Input:        BIBFILE   -- BibTeX file with pmid and file fields
#               TARGETDIR -- directory to store downloaded PDFs (e.g. ~/References)
# Output:       PDFs in TARGETDIR, symlinks in cwd, failures in unfetched_pmids.tsv
#
# Options:
#   --browser            Enable browser fallback for entries that fail auto-download
#   --proxy-prefix URL   Prepend proxy URL to DOI links (for off-campus access)
#                        Example: https://utk.idm.oclc.org/login?url=
#   --no-auto            Skip Pubmed-Batch-Download phase (browser only)
#   --timeout N          Browser window timeout in seconds (default: 120, 0=none)
#   --unfetched FILE     Log failed entries here (default: unfetched_pmids.tsv
#                        in the script directory)
#   -n, --dry-run        Show what would be done without downloading
#   -v, --verbose        Show extra detail
#   -h, --help           Show this help message
#
# Requirements:
#   - Python 3.9+ (for bib parsing via update.bib.py)
#   - ~/anaconda3/bin/conda + pubmed-batch-downloader-py3 env (for auto phase)
#   - /usr/bin/python3 with python3-gi + gir1.2-webkit2-4.1 (for browser phase)
#   - fetch.pdf.with.browser.py in the same directory as this script
#
# Session:      BibTeX Tools - Browser PDF Fetch
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               Claude Sonnet 4.6
# ============================================================================
set -o pipefail

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ -t 1 ]]; then
    RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m'
    BLUE='\033[0;34m' NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' NC=''
fi

ok()   { echo -e "  ${GREEN}ok${NC}    $*"; }
warn() { echo -e "  ${YELLOW}warn${NC}  $*"; }
err()  { echo -e "  ${RED}err${NC}   $*" >&2; }
info() { echo -e "  ${BLUE}info${NC}  $*"; }

usage() {
    sed -n '/^# Usage:/,/^# Requirements:/p' "${BASH_SOURCE[0]}" \
        | sed 's/^# \{0,1\}//' | head -n -1
    exit 0
}

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
BIBFILE=""
TARGETDIR=""
BROWSER_MODE=0
PROXY_PREFIX=""
NO_AUTO=0
TIMEOUT=120
DRY_RUN=0
VERBOSE=0
UNFETCHED="$SCRIPTDIR/unfetched_pmids.tsv"
WHICHCONDA="pubmed-batch-downloader-py3"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --browser)     BROWSER_MODE=1;      shift ;;
        --proxy-prefix) PROXY_PREFIX="$2"; shift 2 ;;
        --no-auto)     NO_AUTO=1;           shift ;;
        --timeout)     TIMEOUT="$2";        shift 2 ;;
        --unfetched)   UNFETCHED="$2";      shift 2 ;;
        -n|--dry-run)  DRY_RUN=1;           shift ;;
        -v|--verbose)  VERBOSE=1;           shift ;;
        -h|--help)     usage ;;
        -*)  err "Unknown option: $1"; exit 1 ;;
        *)
            if [[ -z "$BIBFILE" ]];   then BIBFILE="$1"
            elif [[ -z "$TARGETDIR" ]]; then TARGETDIR="$1"
            else err "Unexpected argument: $1"; exit 1
            fi
            shift ;;
    esac
done

if [[ -z "$BIBFILE" || -z "$TARGETDIR" ]]; then
    err "Usage: $0 [OPTIONS] BIBFILE TARGETDIR"
    err "Run with -h for full help."
    exit 1
fi

if [[ ! -f "$BIBFILE" ]]; then
    err "BIBFILE not found: $BIBFILE"
    exit 1
fi

if [[ ! -d "$TARGETDIR" ]]; then
    err "TARGETDIR not found: $TARGETDIR"
    exit 1
fi

# ---------------------------------------------------------------------------
# Check auto-download prerequisites
# ---------------------------------------------------------------------------
CONDA_OK=0
if [[ $NO_AUTO -eq 0 ]]; then
    if [[ ! -d "$HOME/Repositories/Pubmed-Batch-Download/" ]]; then
        warn "Pubmed-Batch-Download not found -- skipping auto phase."
        warn "Clone https://github.com/billgreenwald/Pubmed-Batch-Download.git to ~/Repositories/"
        CONDA_OK=0
    elif "$HOME/anaconda3/bin/conda" run -n "$WHICHCONDA" python --version \
            >/dev/null 2>&1; then
        CONDA_OK=1
    else
        warn "Conda env '$WHICHCONDA' not ready -- skipping auto phase."
        warn "Run: conda env create -f pubmed-batch-downloader-py3.yml"
        CONDA_OK=0
    fi
fi

# ---------------------------------------------------------------------------
# Check browser prerequisites
# ---------------------------------------------------------------------------
if [[ $BROWSER_MODE -eq 1 ]]; then
    if [[ ! -f "$SCRIPTDIR/fetch.pdf.with.browser.py" ]]; then
        err "fetch.pdf.with.browser.py not found in $SCRIPTDIR"
        exit 1
    fi
    if ! /usr/bin/python3 -c \
            "import gi; gi.require_version('WebKit2','4.1'); \
             from gi.repository import WebKit2" 2>/dev/null; then
        err "WebKit2 not available in /usr/bin/python3"
        err "Install: sudo apt install python3-gi gir1.2-webkit2-4.1"
        exit 1
    fi
fi

# ---------------------------------------------------------------------------
# Extract (pmid, doi, filename) triplets from bib file
# ---------------------------------------------------------------------------
info "Parsing $BIBFILE ..."

ENTRIES_TSV=$(python3 - "$BIBFILE" "$SCRIPTDIR" <<'PYEOF'
import sys, importlib.util, re, os

bib_file = sys.argv[1]
script_dir = sys.argv[2]

# Import parse_bibtex_string from update.bib.py
spec = importlib.util.spec_from_file_location(
    "update_bib", os.path.join(script_dir, "update.bib.py")
)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

with open(bib_file) as f:
    text = f.read()

for entry in mod.parse_bibtex_string(text):
    pmid = entry.get('pmid', '').strip()
    doi  = entry.get('doi',  '').strip()
    file_field = entry.get('file', '')
    m = re.search(r'References/([^:{}\s]+\.pdf)', file_field)
    if pmid and m:
        print(f"{pmid}\t{doi}\t{m.group(1)}")
PYEOF
)

if [[ $? -ne 0 || -z "$ENTRIES_TSV" ]]; then
    err "Failed to extract entries from $BIBFILE"
    exit 1
fi

total=$(echo "$ENTRIES_TSV" | wc -l)
info "Found $total entries with PMID + file fields"

# ---------------------------------------------------------------------------
# Ensure unfetched log has a header
# ---------------------------------------------------------------------------
if [[ ! -f "$UNFETCHED" ]]; then
    echo -e "pmid\tdoi\tfilename\tstatus\tdate" > "$UNFETCHED"
elif [[ ! -s "$UNFETCHED" ]]; then
    echo -e "pmid\tdoi\tfilename\tstatus\tdate" > "$UNFETCHED"
fi

# ---------------------------------------------------------------------------
# Main download loop
# ---------------------------------------------------------------------------
count_auto=0
count_browser=0
count_skip=0
count_fail=0

echo ""
while IFS=$'\t' read -r pmid doi filename; do
    target="$TARGETDIR/$filename"

    # Skip if already in place
    if [[ -f "$target" ]]; then
        [[ $VERBOSE -eq 1 ]] && info "skip  $filename (already exists)"
        count_skip=$((count_skip + 1))
        continue
    fi

    echo -e "  ${BLUE}----${NC} PMID $pmid  $filename"

    if [[ $DRY_RUN -eq 1 ]]; then
        info "dry-run: would attempt download"
        continue
    fi

    auto_ok=0

    # --- Phase 1: Pubmed-Batch-Download ---
    if [[ $NO_AUTO -eq 0 && $CONDA_OK -eq 1 ]]; then
        rm -f "/tmp/$pmid.pdf"
        "$HOME/anaconda3/bin/conda" run -n "$WHICHCONDA" \
            python3.7 "$HOME/Repositories/Pubmed-Batch-Download/fetch_pdfs.py" \
            -pmids "$pmid" -out /tmp/ >/dev/null 2>&1
        if [[ -f "/tmp/$pmid.pdf" ]]; then
            cp "/tmp/$pmid.pdf" "$target"
            if [[ $? -eq 0 ]]; then
                auto_ok=1
                rm -f "/tmp/$pmid.pdf"
            fi
        fi
    fi

    if [[ $auto_ok -eq 1 ]]; then
        ln -sf "$target" "$filename"
        ok "auto    $filename"
        count_auto=$((count_auto + 1))
        continue
    fi

    # --- Phase 2: Browser ---
    if [[ $BROWSER_MODE -eq 1 ]]; then
        if [[ -n "$doi" ]]; then
            paper_url="https://doi.org/$doi"
        else
            paper_url="https://pubmed.ncbi.nlm.nih.gov/$pmid/"
        fi

        info "Opening browser for PMID $pmid  ($paper_url)"

        proxy_args=()
        [[ -n "$PROXY_PREFIX" ]] && proxy_args=(--proxy-prefix "$PROXY_PREFIX")

        /usr/bin/python3 "$SCRIPTDIR/fetch.pdf.with.browser.py" \
            "$paper_url" "$target" \
            "${proxy_args[@]}" \
            --timeout "$TIMEOUT"

        if [[ -f "$target" && -s "$target" ]]; then
            ln -sf "$target" "$filename"
            ok "browser $filename"
            count_browser=$((count_browser + 1))
            continue
        fi
    fi

    # --- Failed ---
    warn "FAILED  PMID $pmid  $filename"
    echo -e "$pmid\t$doi\t$filename\tfailed\t$(date +%Y-%m-%d)" >> "$UNFETCHED"
    count_fail=$((count_fail + 1))

done <<< "$ENTRIES_TSV"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
info "Done.  auto: $count_auto  browser: $count_browser  skipped: $count_skip  failed: $count_fail"
if [[ $count_fail -gt 0 ]]; then
    info "Failed entries logged to: $UNFETCHED"
fi

exit 0
