#!/bin/bash
# ============================================================================
# Script:       make.2x1.and.link.pdf.sh
# Version:      1.2.0
# Revised:      2026-08-04
# Purpose:      Make an n-up (2x1, 2x2, 3x2, ...) version of a PDF
#
# Layout is selected by the name used to invoke the script: the file is
# symlinked as make.2x1.sh, make.2x2.sh, make.2x2L.sh, make.2x3.sh,
# make.3x2.sh, make.3x3.sh, make.4x1.sh, make.4x3.sh, make.5x3.sh, and the
# case block below dispatches on "$(basename $0)".
#
# NOTE on the layout labels: in this script the label is ROWSxCOLS-ish and
# does not match pdfnup's COLSxROWS convention.  E.g. make.2x3.sh sets
# COL=3, ROW=2, whereas "pdfnup --nup 2x3" means 2 columns by 3 rows.
#
# When invoked as *.and.link.pdf.sh the output is moved to ~/References/
# and symlinked back into the current directory.
#
# Usage:        make.<layout>.sh [--no-recompress] [pdfxup options] FILE.pdf
# Input:        A PDF file (last argument).  Any earlier arguments are
#               passed through to pdfxup.
# Output:       FILE-<layout>.pdf in the current directory
#
# Options:
#   --no-recompress   Skip the ghostscript pass (see below)
#
# Ghostscript pass (added 1.1.0; moved to a shared helper in 1.2.0):
#   pdfxup inflates output 15-60x on PDFs exported from ODP slides.  A
#   ghostscript rewrite recovers the size with the crop intact.  The full
#   explanation and the safety guards live in pdf.recompress.sh, which this
#   script sources.  Opt out with --no-recompress or PDFTOOLS_NO_RECOMPRESS;
#   override the quality preset with PDFTOOLS_GS_SETTING.
#
# Requirements:
#   - pdfxup (TeX Live package "pdfxup"), pdfinfo, pdfcrop
#   - pdf.recompress.sh alongside this script
#   - gs (optional; without it the output is left uncompressed)
#
# AI Model:     Claude Opus 5
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 5
# ============================================================================

# Scratch directory.  Honors TMPDIR so the script works where /tmp is not
# writable (sandboxes, hardened hosts); falls back to /tmp as before.
TMPD="${TMPDIR:-/tmp}"
TMPD="${TMPD%/}"

# Shared ghostscript recompression helper.  Resolve through $0 so this works
# when invoked via the ~/bin symlinks; readlink -f is used only to find the
# real directory and does NOT affect the basename dispatch below.
SRCDIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
if [[ -r "$SRCDIR/pdf.recompress.sh" ]]; then
    . "$SRCDIR/pdf.recompress.sh"
else
    echo "[WARN] $SRCDIR/pdf.recompress.sh not found; recompression disabled"
    pdf_recompress() { return 1; }
fi

# --- Options consumed by this script (everything else goes to pdfxup) -----
RECOMPRESS=1
[[ -n "$PDFTOOLS_NO_RECOMPRESS" || -n "$MAKEXUP_NO_RECOMPRESS" ]] && RECOMPRESS=0
GS_SETTING="${PDFTOOLS_GS_SETTING:-${MAKEXUP_GS_SETTING:-/prepress}}"

ARGS=()
for arg in "$@"; do
    case "$arg" in
        --no-recompress) RECOMPRESS=0 ;;
        *) ARGS+=("$arg") ;;
    esac
done
set -- "${ARGS[@]}"

if [[ "$#" -lt 1 ]]; then
    echo "Error in $0:  A minimum of one argument expected: <FILE.pdf>";
    exit 1;
fi

CMD="$(basename $0)";

echo "$CMD"

case "$CMD" in
    *.2x2.sh)
    COL=2;
    ROW=2;
    FW=0;
    LND=0; # would have expected it to be 1...
    SUFF="2x2";
    MAR=5;
    ISP=0;
    ;;
    *.2x2L.sh)
    COL=2;
    ROW=2;
    FW=0;
    LND=1; # would have expected it to be 1...
    SUFF="2x2L";
    MAR=5;
    ISP=0;
    ;;
   *.2x1.sh)
    COL=2;
    ROW=1;
    FW=0;
    LND=1;
    SUFF="2x1";
    MAR=25;
    ISP=10;
    ;;
   *3x2.sh)
    COL=2;
    ROW=3;
    FW=0;
    LND=1;
    SUFF="3x2";
    MAR=5;
    ISP=0;
    ;;
   *2x3.sh)
    COL=3;
    ROW=2;
    FW=0;
    LND=0;
    SUFF="2x3";
    MAR=5;
    ISP=0;
    ;;
   *3x3.sh)
    COL=3;
    ROW=3;
    FW=0;
    LND=0;
    SUFF="3x3";
    MAR=5;
    ISP=0;
    ;;
   *4x3.sh)
    COL=3;
    ROW=4;
    FW=0;
    LND=0;
    SUFF="4x3";
    MAR=5;
    ISP=0;
    ;;
   *5x3.sh)
    COL=3;
    ROW=5;
    FW=0;
    LND=0;
    SUFF="5x3";
    MAR=5;
    ISP=0;
    ;;

    *)
      echo "Unrecognized command: file not processed"
      ;;
esac

       #echo "SUFF= $SUFF"
       
## assume file is last argument

    
FILE="${@: -1}";
echo "FILE = $FILE"

OPTARGS="${@:1:${#}-1}"
# I thought OPTARGS might have newlines, but it doesn't seem to
#OPTARGS=${OPTARGS/$'\n'/ /}

echo "OPTARGS = $OPTARGS; length = ${#OPTARGS}"

TMPFILE="tmp-$(basename $FILE)"
NEWFILE="${FILE/.pdf/-$SUFF.pdf}"

## Commented out after add $OPTARGS
#PAGES=$(pdfinfo $FILE | grep "^Pages" | awk '{print $2}')
### Truncate if long file
#if [[ $PAGES -ge 20 ]]; then
#    PAGES=20
#fi

#Use page 2 by default
# Commented out due to ability to pass arguments
# PAGES=2
#"2-3"
#echo "Pages: $PAGES"
echo "Tmp File: $TMPFILE"
echo "New File: $NEWFILE"

cp -Lf "$FILE" "$TMPD/$TMPFILE"  || { echo "Failed to copy $FILE to $TMPD/$TMPFILE; Exiting"; exit 1; } # need to use {\  and \ } [note spaces] and not () (which starts a subshell)

# Detect offset CropBox: pdfxup uses ghostscript to compute the content bounding box,
# which reports coordinates in MediaBox space.  pdflatex's viewport= option interprets
# those coordinates in CropBox-relative space (origin = CropBox lower-left).  When the
# CropBox lower-left is not at (0,0) the two coordinate systems disagree, causing pdfxup
# to clip content at the wrong edges.  Pre-cropping with pdfcrop normalizes the PDF so
# MediaBox == visible area, eliminating the mismatch.
NEEDS_CROP=$(pdfinfo -box "$TMPD/$TMPFILE" 2>/dev/null | awk '
    /^CropBox:/ { if ($2+0 > 0.5 || $3+0 > 0.5) print "yes" }')
if [[ "$NEEDS_CROP" == "yes" ]]; then
    echo "Offset CropBox detected; pre-cropping to normalize coordinates..."
    CROPPEDTMP="tmp-precrop-$(basename "$FILE")"
    if pdfcrop --margins 0 "$TMPD/$TMPFILE" "$TMPD/$CROPPEDTMP"; then
        rm -f "$TMPD/$TMPFILE"
        TMPFILE="$CROPPEDTMP"
        echo "Pre-crop complete; using $TMPD/$TMPFILE"
    else
        echo "[WARN] pdfcrop failed; proceeding without pre-crop (output may have misaligned text)"
    fi
fi


# -V: Verbosity
# -fw: Frame weight
# -m: Margins of new document
# -is: interspace between pages
# -nc : no clipping or -c 0
# Had to remove #  -bb 1-$PAGES \
# 2023-03-21: Changed from ~/bin/pdfxup-local to pdfxup
pdfxup \
  -V 2 \
  -fw "$FW" \
  -m "$MAR" \
  -l "$LND" \
  -x "$COL" \
  -y "$ROW" \
  -is "$ISP" \
  -ps "letter" \
  -o pdfxup.pdf $OPTARGS "$TMPD/$TMPFILE" || { echo "Failed to run pdfxup on $TMPD/$TMPFILE; Exiting"; exit 1; }
# NOTE: Don't put quotes around $OPTARGS.  That screws things up, I don't kvnow why.
#       Perhaps because it is already a string?
#
#       pdfxup.pdf should be in current dir
# 
#       Because I am using an alias for pdfxup, there's an issue with the exit code from pdfxup not being properly passed.

# This doesn't work
# Shouldn't need it give || statement at end of pdfxup command
#if [ $? -ne 0 ]; then
#	echo "pdfxup command failed. Exiting
#	exit 1
#fi

echo "Removing temporary file $TMPD/$TMPFILE"
rm -f "$TMPD/$TMPFILE" || { echo "Failed to remove $TMPD/$TMPFILE ; Exiting"; exit 1; }
mv "pdfxup.pdf" "$NEWFILE"  || { echo "Failed to copy pdfxup.pdf to $NEWFILE"; exit 1; }

## Ghostscript recompression pass.  See pdf.recompress.sh for why this is
## needed and for the guards that keep it from damaging a good result.
if [[ "$RECOMPRESS" -eq 1 ]]; then
    pdf_recompress "$NEWFILE" "$GS_SETTING"
fi

## Was the input itself a scratch file?  Check both TMPDIR and /tmp, so the
## prompt still fires for a file sitting in /tmp when TMPDIR points elsewhere.
if [[ "$FILE" == "$TMPD/"* || "$FILE" == "/tmp/"* ]]; then
    echo "Move $NEWFILE to local directory? (y)/n"
    read TMP;
    if [[ $TMP != "n" || $TMP != "N" ]]; then
        echo "Moving $NEWFILE to $PWD";
        mv "$NEWFILE" .;
    fi
fi

if [[ "$0" = *.and.link.pdf.sh ]]; then 
    mv "$NEWFILE" "$HOME/References/" || { echo "Failed to mv $NEWFILE to ~/References"; exit 1; }
    ln -s "$HOME/References/$NEWFILE" . || { echo "Failed to link ~/References/$NEWFILE to local dir"; exit 1; }

    echo "Use copy.target.and.redirect.links.sh to alter where link points? (useful for working with repos)? [y/n]"
    read TMP;
    if [[ $TMP == "y" || $TMP == "Y" ]]; then
        #    declare -a LINKSCREATED=(); #create an array # this doesn't need to be here
        echo "Enter new location for target. (default \"../../References/\")";
        read TARGET;
        if [[ "$TARGET" == "" ]]; then
            TARGET="../../References/";
        fi
        copy.target.and.redirect.links.sh "$NEWFILE" "$TARGET" || { echo "Failed to copy.target.and.redirect.links.sh for $NEWFILE and"; exit 1; }
    fi
fi
