#!/bin/bash
# ============================================================================
# Script:       pdf.recompress.sh
# Version:      1.0.0
# Created:      2026-08-04
# Revised:      2026-08-04
# Purpose:      Sourceable helper: shrink a PDF with ghostscript, safely
#
# Why this exists
# ---------------
# pdfxup and pdfcrop rebuild a document through pdflatex using per-page
# \includegraphics[viewport=...] clipping.  On PDFs exported from ODP
# slides that path re-embeds shared image resources once per page instead
# of sharing them, inflating output by 15-60x.  Measured 2026-08-04 on a
# 3.75 MB lecture deck: pdfxup at 2x2 produced 117.67 MB, pdfcrop alone
# produced 231.52 MB.  pdfjam, which includes the file in a single call,
# does not inflate.
#
# A ghostscript rewrite deduplicates the repeated image XObjects and
# recovers the size with the crop and page count intact.
#
# Usage:        source pdf.recompress.sh
#               pdf_recompress FILE.pdf [GS_SETTING]
#
# Input:        A PDF file, rewritten in place only if the result is sound
# Output:       Stdout: a one-line size report, or a [WARN] on any problem
#
# Returns:      0 if the file was replaced with a smaller version
#               1 if the original was left untouched (any reason)
#               Never exits the calling shell -- a failure here should not
#               destroy an otherwise good n-up result.
#
# Environment:
#   PDFTOOLS_GS_SETTING   quality preset, default /prepress (the least
#                         lossy preset that still downsamples >300 dpi)
#   PDFTOOLS_NO_RECOMPRESS   if set, pdf_recompress returns 1 immediately
#   MAKEXUP_GS_SETTING / MAKEXUP_NO_RECOMPRESS
#                         honored as deprecated aliases of the above
#
# Requirements:
#   - gs, pdfinfo  (absent gs is a warning, not an error)
#
# Session:      Genetics F.2026 prep
# AI Model:     Claude Opus 5
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 5
# ============================================================================

pdf_recompress() {
    local file="$1"
    local setting="$2"

    [[ -n "$PDFTOOLS_NO_RECOMPRESS" || -n "$MAKEXUP_NO_RECOMPRESS" ]] && return 1

    if [[ -z "$setting" ]]; then
        setting="${PDFTOOLS_GS_SETTING:-${MAKEXUP_GS_SETTING:-/prepress}}"
    fi

    if [[ ! -f "$file" ]]; then
        echo "[WARN] pdf_recompress: no such file: $file"
        return 1
    fi

    if ! command -v gs &>/dev/null; then
        echo "[WARN] gs not found; skipping recompression (output may be large)"
        return 1
    fi

    local size_before pages_before size_after pages_after tmp
    size_before=$(stat -c%s "$file" 2>/dev/null)
    pages_before=$(pdfinfo "$file" 2>/dev/null | awk '/^Pages:/ {print $2}')
    tmp="$(dirname "$file")/.gsrecompress-$$-$(basename "$file")"

    echo "Recompressing with gs ($setting)..."
    if ! gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 \
            -dPDFSETTINGS="$setting" \
            -dNOPAUSE -dQUIET -dBATCH \
            -sOutputFile="$tmp" "$file" 2>/dev/null; then
        echo "[WARN] gs failed; keeping the original"
        rm -f "$tmp"
        return 1
    fi

    size_after=$(stat -c%s "$tmp" 2>/dev/null)
    pages_after=$(pdfinfo "$tmp" 2>/dev/null | awk '/^Pages:/ {print $2}')

    # Every check below leaves the original in place.  A recompression pass
    # must never be able to damage a result that was already correct.
    if [[ -z "$size_after" || "$size_after" -eq 0 ]]; then
        echo "[WARN] gs produced an empty file; keeping the original"
        rm -f "$tmp"
        return 1
    elif [[ "$pages_before" != "$pages_after" ]]; then
        echo "[WARN] page count changed ($pages_before -> $pages_after); keeping the original"
        rm -f "$tmp"
        return 1
    elif [[ "$size_after" -ge "$size_before" ]]; then
        echo "  No reduction ($(( size_before / 1024 )) KB -> $(( size_after / 1024 )) KB); keeping the original"
        rm -f "$tmp"
        return 1
    fi

    if ! mv "$tmp" "$file"; then
        echo "[WARN] failed to install recompressed file; keeping the original"
        rm -f "$tmp"
        return 1
    fi

    echo "  Size: $(( size_before / 1024 )) KB -> $(( size_after / 1024 )) KB ($pages_after pages)"
    return 0
}
