#! /bin/bash
# ============================================================================
# Script:       pdfxupn.sh
# Version:      1.1.0
# Revised:      2026-08-04
# Purpose:      n-up a PDF with pdfxup, then add centered page numbers
#
# Two passes: pdfxup crops and lays out the pages, then pdfjam stamps a
# centered footer page number via fancyhdr.  Finally the result is shrunk
# with ghostscript -- pdfxup inflates output 15-60x on PDFs exported from
# ODP slides.  See pdf.recompress.sh for the explanation and the guards
# that keep that pass from damaging a good result.
#
# Related: add.page.numbers.to.pdf.sh stamps page numbers onto an existing
# PDF (enscript + pdftk) without doing any n-up.  Use that one when the
# layout is already correct.
#
# Usage:        pdfxupn.sh <input.pdf> [output.pdf]
# Input:        A PDF file.  Default output is ./pdfxupn.pdf
# Output:       The n-upped, page-numbered PDF
#
# Environment:
#   PDFTOOLS_NO_RECOMPRESS   skip the ghostscript pass
#   PDFTOOLS_GS_SETTING      quality preset (default /prepress)
#
# Requirements:
#   - pdfxup (TeX Live package "pdfxup"), pdfjam
#   - pdf.recompress.sh alongside this script
#   - gs (optional; without it the output is left uncompressed)
#
# Session:      Genetics F.2026 prep
# AI Model:     Claude Opus 5
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 5
# ============================================================================

if [ "$#" -lt 1 ]; then
    echo "Error in $0:  At least one argument <input.pdf> expected"
    exit 1
else if [ "$#" -gt 2 ]; then
	 echo "Error in $0:  Up to two arguments allowed:  <input.pdf> <output.pdf>"
	 exit 1
     fi
fi

## Resolve pdfxup from PATH.  It ships with TeX Live (package "pdfxup") and
## lives under texmf-dist/scripts/pdfxup/, not /usr/bin, so the previous
## hardcoded /usr/bin/pdfxup did not exist on any current machine.
if ! command -v pdfxup &>/dev/null; then
    echo "Error in $0:  pdfxup not found in PATH." >&2
    echo "  It is a TeX Live package; install with: tlmgr install pdfxup" >&2
    exit 1
fi

## Shared ghostscript recompression helper.  Resolve through $0 so this
## works when invoked via the ~/bin symlink.
SRCDIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
if [ -r "$SRCDIR/pdf.recompress.sh" ]; then
    . "$SRCDIR/pdf.recompress.sh"
else
    echo "[WARN] $SRCDIR/pdf.recompress.sh not found; recompression disabled"
    pdf_recompress() { return 1; }
fi

INPUT="$1"
TMP="${TMPDIR:-/tmp}/tmppdfxup-$$.pdf"

if [ "$#" -gt 1 ]; then
    OUTPUT="$2"
else
    OUTPUT="pdfxupn.pdf"
fi

echo "$INPUT"

pdfxup -ps letter -m 20 -im 20 -fw 0 -o "$TMP" "$INPUT" || { echo "Error in $0:  pdfxup failed on $INPUT" >&2; rm -f "$TMP"; exit 1; }
pdfjam --nup 1x1 --landscape --pagecommand '\thispagestyle{plain} \cfoot{\thepage}' --preamble '\usepackage{fancyhdr} \topmargin 85pt \pagestyle{fancy} ' -o "$OUTPUT" "$TMP" || { echo "Error in $0:  pdfjam failed" >&2; rm -f "$TMP"; exit 1; }
rm -f "$TMP"

## Undo pdfxup's size inflation.  Non-destructive; see pdf.recompress.sh.
pdf_recompress "$OUTPUT"

echo "Created: $OUTPUT"


