#!/bin/bash
# ============================================================================
# Script:       prepend.bib.pl
# Version:      2.0.0
# Date:         2026-03-23
# Purpose:      Convert ISI records to BibTeX and prepend to master bibliography
#
# Converts /tmp/savedrecs.txt via isi2bibtex, then prepends new entries
# to ~/BiBTeX/bibliography.full.bib. Optionally downloads PDFs via PMID.
#
# Usage:        prepend.bib.pl [OPTIONS]
# Input:        /tmp/savedrecs.txt (ISI format)
# Output:       Updated ~/BiBTeX/bibliography.full.bib, /tmp/tmp.bib
#
# Options:
#   -b, --batch     Non-interactive mode (auto-yes to all prompts)
#   -h, --help      Show this help message
#
# Requirements:
#   - ~/bin/isi2bibtex
#   - ~/bin/get.pdf.from.bib.pmid.sh (for PDF downloads)
#
# Session:      S17 Cancer Evolution prep
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

set -o pipefail

# --- Color output ---
if [[ -t 1 ]]; then
    RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m'
    BLUE='\033[0;34m' NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' NC=''
fi

ok()   { echo -e "  ${GREEN}ok${NC}  $*"; }
warn() { echo -e "  ${YELLOW}warn${NC} $*"; }
err()  { echo -e "  ${RED}err${NC}  $*" >&2; }

# --- Defaults ---
BATCH=0
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
ISITMPFILE="/tmp/isi-tmpfile"
TMPBIB="/tmp/tmp.bib"
BIBFILE="$HOME/BiBTeX/bibliography.full.bib"
BKUPDIR="$HOME/BiBTeX/Bkups"

# --- Parse options ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        -b|--batch) BATCH=1; shift ;;
        -h|--help)
            echo "Usage: $(basename "$0") [OPTIONS]"
            echo ""
            echo "Convert /tmp/savedrecs.txt to BibTeX and prepend to bibliography."
            echo ""
            echo "Options:"
            echo "  -b, --batch     Non-interactive mode (auto-yes to all prompts)"
            echo "  -h, --help      Show this help message"
            exit 0
            ;;
        *)
            err "Unknown option: $1"
            exit 1
            ;;
    esac
done

# --- Confirm input exists ---
if [[ ! -f /tmp/savedrecs.txt ]]; then
    err "/tmp/savedrecs.txt does not exist. Please supply. Exiting"
    exit 1
fi

# --- Handle existing /tmp/tmp.bib ---
if [[ -f "$TMPBIB" ]]; then
    if [[ $BATCH -eq 1 ]]; then
        BACKUP="${TMPBIB}.${TIMESTAMP}.bak"
        warn "$TMPBIB exists, backing up to $BACKUP"
        mv "$TMPBIB" "$BACKUP"
    else
        echo "$TMPBIB already exists."
        echo -n "Remove file and continue? (n): "
        read TMP
        if [[ $TMP == "y" || $TMP == "Y" ]]; then
            echo "Removing $TMPBIB and continuing"
            rm "$TMPBIB"
        else
            echo "Leaving $TMPBIB untouched. Exiting..."
            exit 1
        fi
    fi
fi

# --- Convert ISI -> BibTeX ---
cp -f /tmp/savedrecs.txt "$ISITMPFILE"
~/bin/isi2bibtex "$ISITMPFILE" "$TMPBIB"

if [[ ! -f "$TMPBIB" ]]; then
    err "isi2bibtex failed to produce $TMPBIB"
    exit 1
fi

ok "Created $TMPBIB"

# --- Show output (interactive only) ---
if [[ $BATCH -eq 0 ]]; then
    echo -n "Check isi2bibtex output? (n): "
    read TMP
    if [[ $TMP == "y" || $TMP == "Y" ]]; then
        less "$TMPBIB"
    fi
else
    echo -e "${BLUE}BibTeX output:${NC}"
    head -20 "$TMPBIB"
    echo "  ..."
fi

# --- Prompt to append to bibliography ---
DO_APPEND=0
if [[ $BATCH -eq 1 ]]; then
    DO_APPEND=1
    ok "Auto-appending to $BIBFILE"
else
    echo -n "Append full.bib output to bibliography.full.bib? (n): "
    read TMP
    if [[ $TMP == "y" || $TMP == "Y" ]]; then
        DO_APPEND=1
    fi
fi

if [[ $DO_APPEND -eq 1 ]]; then
    # Prepend new entries (cat new + old -> combined, then replace old)
    cat "$TMPBIB" "$BIBFILE" > /tmp/bibliography.full.bib

    # Backup chain: current bkup -> .bkup, current bib -> bkup, new -> current
    cp -pf "$BKUPDIR/bibliography.full.bib" "$BKUPDIR/bibliography.full.bkup" 2>/dev/null
    cp -pf "$BIBFILE" "$BKUPDIR/bibliography.full.bib"
    cp -pf /tmp/bibliography.full.bib "$BIBFILE"

    ok "Updated $BIBFILE"

    # Archive the ISI input
    mv -f /tmp/savedrecs.txt "/tmp/savedrecs.txt.${TIMESTAMP}.old"

    # --- PDF handling ---
    DO_PMID=0
    if [[ $BATCH -eq 1 ]]; then
        DO_PMID=1
        ok "Auto-downloading PDFs via PMID"
    else
        echo -n "Process previously downloaded PDFs using bib.move.and.link.sh? (n): "
        read TMP
        if [[ $TMP == "y" || $TMP == "Y" ]]; then
            ~/bin/bib.move.and.link.sh
        else
            echo -n "Get papers via PMID, place in ~/References, and link? (n): "
            read TMP
            if [[ $TMP == "y" || $TMP == "Y" ]]; then
                DO_PMID=1
            else
                echo "Not downloading files."
            fi
        fi
    fi

    if [[ $DO_PMID -eq 1 ]]; then
        ~/bin/get.pdf.from.bib.pmid.sh "$TMPBIB" ~/References
    fi

    # --- Cleanup /tmp/tmp.bib ---
    if [[ $BATCH -eq 1 ]]; then
        # Keep it with a timestamped name for reference
        ARCHIVE="${TMPBIB}.${TIMESTAMP}.done"
        mv "$TMPBIB" "$ARCHIVE"
        ok "Archived $TMPBIB to $ARCHIVE"
    else
        echo -n "Remove $TMPBIB? (n): "
        read TMP
        if [[ "$TMP" == "y" || "$TMP" == "Y" ]]; then
            rm -f "$TMPBIB"
        else
            echo "leaving $TMPBIB"
        fi
    fi

    rm -f /tmp/bibliography.full.bib
    rm -f /tmp/abbrv.bib
else
    echo "Leaving files unchanged and not updating bibliography.full.bib"
fi
