#!/bin/bash
# ============================================================================
# Script:       update.bib.sh
# Version:      2.2.0
# Date:         2026-05-01
# Purpose:      Convert .ris files in /tmp to BibTeX and update bibliography
#
# Pipeline: .ris -> ris2xml -> xml2isi -> isi2bibtex -> prepend to bibliography
#
# Usage:        update.bib.sh [OPTIONS] N
# Input:        N newest .ris files in /tmp/
# Output:       Updated ~/BiBTeX/bibliography.full.bib, PDFs in ~/References/,
#               optional .txt extracts in ~/References/Extracts/,
#               optional summary .md files in ~/References/Summaries/
#
# Options:
#   -b, --batch     Non-interactive mode (auto-yes to all prompts)
#   -n, --dry-run   Show what would be done without making changes
#   -v, --verbose   Show detailed output
#   -h, --help      Show this help message
#
# Requirements:
#   - ris2xml and xml2isi in PATH (bibutils)
#   - ~/bin/isi2bibtex (Perl, with ~/.isi2bibtexrc)
#   - ~/bin/prepend.bib.pl
#   - pdftotext (poppler-utils, for .txt extract generation)
#   - claude CLI (for summary .md generation)
#
# Session:      S26b Cancer Evolution prep
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               Claude Sonnet 4.6
# ============================================================================

set -o pipefail

# --- Color output ---
if [[ -t 1 ]]; then
    RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m'
    BLUE='\033[0;34m' NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' NC=''
fi

ok()   { echo -e "  ${GREEN}ok${NC}  $*"; }
warn() { echo -e "  ${YELLOW}warn${NC} $*"; }
err()  { echo -e "  ${RED}err${NC}  $*" >&2; }

# --- Defaults ---
BATCH=0
DRYRUN=0
VERBOSE=0
N=""

# --- Parse options ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        -b|--batch)     BATCH=1; shift ;;
        -n|--dry-run)   DRYRUN=1; shift ;;
        -v|--verbose)   VERBOSE=1; shift ;;
        -h|--help)
            echo "Usage: $(basename "$0") [OPTIONS] N"
            echo ""
            echo "Convert the N newest .ris files in /tmp/ to BibTeX and update bibliography."
            echo ""
            echo "Options:"
            echo "  -b, --batch     Non-interactive mode (auto-yes to all prompts)"
            echo "  -n, --dry-run   Show what would be done without making changes"
            echo "  -v, --verbose   Show detailed output"
            echo "  -h, --help      Show this help message"
            echo ""
            echo "Interactive prompts (in order):"
            echo "  - Remove/backup existing /tmp/savedrecs.txt?"
            echo "  - Check isi2bibtex output? (via prepend.bib.pl)"
            echo "  - Append to bibliography.full.bib? (via prepend.bib.pl)"
            echo "  - Process PDFs or download via PMID? (via prepend.bib.pl)"
            echo "  - Generate .txt and/or summary .md files?"
            exit 0
            ;;
        -*)
            err "Unknown option: $1"
            exit 1
            ;;
        *)
            if [[ -z "$N" ]]; then
                N="$1"
            else
                err "Unexpected argument: $1"
                exit 1
            fi
            shift
            ;;
    esac
done

if [[ -z "$N" ]]; then
    err "One argument expected: N - the number of .ris files to process."
    echo "Usage: $(basename "$0") [OPTIONS] N"
    exit 1
fi

# --- Timestamp for unique filenames ---
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
ISIFILE="/tmp/savedrecs.txt"

# --- Find .ris files (newest first, ignoring already-processed) ---
readarray -t RISFILES <<<"$(ls -t /tmp/*.ris --ignore "*-used.ris" 2>/dev/null)"

# Filter out empty entries
VALID_RISFILES=()
for f in "${RISFILES[@]}"; do
    [[ -n "$f" && -f "$f" ]] && VALID_RISFILES+=("$f")
done
RISFILES=("${VALID_RISFILES[@]}")

if [[ $VERBOSE -eq 1 ]]; then
    echo -e "${BLUE}All matching .ris files in /tmp${NC}"
    printf '  %s\n' "${RISFILES[@]}"
    echo "  Count: ${#RISFILES[@]}"
fi

if [[ "${#RISFILES[@]}" -lt "$N" ]]; then
    err "Requested $N .ris files but only ${#RISFILES[@]} found in /tmp/"
    exit 1
fi

# --- Take the first N ---
RISFILES=("${RISFILES[@]:0:N}")

if [[ $VERBOSE -eq 1 || $DRYRUN -eq 1 ]]; then
    echo -e "${BLUE}Processing $N .ris file(s):${NC}"
    printf '  %s\n' "${RISFILES[@]}"
fi

# --- Handle pre-existing ISI file ---
if [[ -f "$ISIFILE" ]]; then
    if [[ $BATCH -eq 1 ]]; then
        BACKUP="${ISIFILE}.${TIMESTAMP}.bak"
        warn "$ISIFILE exists, backing up to $BACKUP"
        if [[ $DRYRUN -eq 0 ]]; then
            mv "$ISIFILE" "$BACKUP"
        fi
    else
        echo "$ISIFILE already exists."
        echo -n "Remove file and continue? (n): "
        read TMP
        if [[ $TMP == "y" || $TMP == "Y" ]]; then
            echo "Removing $ISIFILE and continuing"
            rm "$ISIFILE"
        else
            echo "Leaving $ISIFILE untouched. Exiting..."
            exit 1
        fi
    fi
fi

# --- Convert RIS -> ISI ---
if [[ $DRYRUN -eq 1 ]]; then
    echo -e "${BLUE}[dry-run] Would convert ${#RISFILES[@]} .ris files to $ISIFILE${NC}"
else
    for FILE in "${RISFILES[@]}"; do
        [[ $VERBOSE -eq 1 ]] && echo -e "  Converting: $FILE"
        ris2xml "$FILE" | xml2isi -nb >> "$ISIFILE"
        if [[ $? -ne 0 ]]; then
            err "Failed to convert: $FILE"
        fi
    done
    ok "Created $ISIFILE from ${#RISFILES[@]} .ris file(s)"

    # --- Inject PM (PMID) lines lost by xml2isi ---
    # xml2isi versions <= 7.2 have no mapping for PubMed IDs; patch them in
    # by matching DI (DOI). Skipped automatically once a fixed bibutils is
    # installed (probe converts a synthetic RIS record and checks for PM output).
    if printf 'TY  - JOUR\nPM  - 99999999\nER  -\n' \
            | ris2xml 2>/dev/null | xml2isi -nb 2>/dev/null \
            | grep -q '^PM '; then
        [[ $VERBOSE -eq 1 ]] && ok "bibutils has native PM support -- skipping injection"
    else
    python3 - "${RISFILES[@]}" "$ISIFILE" << 'PYEOF'
import re, sys

ris_files = sys.argv[1:-1]
isi_file  = sys.argv[-1]

# Build DOI -> PMID map from RIS files
doi_to_pmid = {}
for path in ris_files:
    doi = pmid = None
    with open(path) as fh:
        for line in fh:
            m = re.match(r'^DO\s+-\s+(.+)', line)
            if m: doi = m.group(1).strip()
            m = re.match(r'^PM\s+-\s+(.+)', line)
            if m: pmid = m.group(1).strip()
    if doi and pmid:
        doi_to_pmid[doi] = pmid

if not doi_to_pmid:
    sys.exit(0)

with open(isi_file) as f:
    lines = f.readlines()

current_doi = None
out = []
injected = 0
for line in lines:
    stripped = line.rstrip()
    m = re.match(r'^DI (.+)', stripped)
    if m:
        current_doi = m.group(1).strip()
    if stripped == 'ER' and current_doi in doi_to_pmid:
        out.append('PM ' + doi_to_pmid[current_doi] + '\n')
        injected += 1
        current_doi = None
    out.append(line)

with open(isi_file, 'w') as f:
    f.writelines(out)

print(f'  Injected PM field for {injected} of {len(doi_to_pmid)} RIS records with PMIDs')
PYEOF
    [[ $VERBOSE -eq 1 ]] && ok "PM injection complete"
    fi  # end bibutils PM workaround
fi

# --- Run prepend.bib.pl ---
if [[ $DRYRUN -eq 1 ]]; then
    echo -e "${BLUE}[dry-run] Would run prepend.bib.pl${NC}"
    [[ $BATCH -eq 1 ]] && echo -e "${BLUE}[dry-run]   with --batch flag${NC}"
else
    echo -e "\n${BLUE}Running prepend.bib.pl...${NC}"
    if [[ $BATCH -eq 1 ]]; then
        ~/bin/prepend.bib.pl --batch
    else
        ~/bin/prepend.bib.pl
    fi
fi

# --- Generate .txt and/or summary .md files ---
GEN_MODE=""
if [[ $BATCH -eq 1 ]]; then
    GEN_MODE="both"
elif [[ $DRYRUN -eq 0 ]]; then
    echo -n "Generate .txt and/or summary .md files? (extract/summary/both/n) (n): "
    read -r TMP
    case "$TMP" in
        both|y|Y)              GEN_MODE="both" ;;
        extract|txt|TXT)       GEN_MODE="txt" ;;
        summary|md|MD|sum|SUM) GEN_MODE="md" ;;
        *)             GEN_MODE="" ;;
    esac
fi

if [[ -n "$GEN_MODE" ]]; then
    # Build list of /tmp source files matching each .ris basename
    GEN_ARGS=()
    for FILE in "${RISFILES[@]}"; do
        BASE=$(basename "$FILE" .ris)
        if [[ -f "/tmp/${BASE}.pdf" ]]; then
            GEN_ARGS+=("/tmp/${BASE}.pdf")
        elif [[ -f "/tmp/${BASE}.txt" ]]; then
            GEN_ARGS+=("/tmp/${BASE}.txt")
        else
            warn "No matching .pdf or .txt in /tmp for $BASE -- skipping"
        fi
    done

    if [[ ${#GEN_ARGS[@]} -gt 0 ]]; then
        SUMMARIZE_OPTS=()
        [[ "$GEN_MODE" == "txt" ]] && SUMMARIZE_OPTS+=(--no-summary)
        [[ "$GEN_MODE" == "md"  ]] && SUMMARIZE_OPTS+=(--no-extract)
        [[ $BATCH -eq 1 ]]         && SUMMARIZE_OPTS+=(--batch)
        [[ $DRYRUN -eq 1 ]]        && SUMMARIZE_OPTS+=(--dry-run)
        [[ $VERBOSE -eq 1 ]]       && SUMMARIZE_OPTS+=(--verbose)

        summarize.files "${SUMMARIZE_OPTS[@]}" "${GEN_ARGS[@]}"
    fi
fi

# --- Mark .ris files as used ---
if [[ $DRYRUN -eq 0 ]]; then
    for FILE in "${RISFILES[@]}"; do
        USEDFILE="${FILE%.ris}-used.ris"
        mv "$FILE" "$USEDFILE"
        [[ $VERBOSE -eq 1 ]] && ok "Marked as used: $USEDFILE"
    done
fi

exit 0
