#!/bin/bash
# ============================================================================
# Script:       update.bib.sh
# Version:      2.0.0
# Date:         2026-03-23
# Purpose:      Convert .ris files in /tmp to BibTeX and update bibliography
#
# Pipeline: .ris -> ris2xml -> xml2isi -> isi2bibtex -> prepend to bibliography
#
# Usage:        update.bib.sh [OPTIONS] N
# Input:        N newest .ris files in /tmp/
# Output:       Updated ~/BiBTeX/bibliography.full.bib, PDFs in ~/References/
#
# Options:
#   -b, --batch     Non-interactive mode (auto-yes to all prompts)
#   -n, --dry-run   Show what would be done without making changes
#   -v, --verbose   Show detailed output
#   -h, --help      Show this help message
#
# Requirements:
#   - ris2xml and xml2isi in PATH (bibutils)
#   - ~/bin/isi2bibtex (Perl, with ~/.isi2bibtexrc)
#   - ~/bin/prepend.bib.pl
#
# Session:      S17 Cancer Evolution prep
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

set -o pipefail

# --- Color output ---
if [[ -t 1 ]]; then
    RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m'
    BLUE='\033[0;34m' NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' NC=''
fi

ok()   { echo -e "  ${GREEN}ok${NC}  $*"; }
warn() { echo -e "  ${YELLOW}warn${NC} $*"; }
err()  { echo -e "  ${RED}err${NC}  $*" >&2; }

# --- Defaults ---
BATCH=0
DRYRUN=0
VERBOSE=0
N=""

# --- Parse options ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        -b|--batch)     BATCH=1; shift ;;
        -n|--dry-run)   DRYRUN=1; shift ;;
        -v|--verbose)   VERBOSE=1; shift ;;
        -h|--help)
            echo "Usage: $(basename "$0") [OPTIONS] N"
            echo ""
            echo "Convert the N newest .ris files in /tmp/ to BibTeX and update bibliography."
            echo ""
            echo "Options:"
            echo "  -b, --batch     Non-interactive mode (auto-yes to all prompts)"
            echo "  -n, --dry-run   Show what would be done without making changes"
            echo "  -v, --verbose   Show detailed output"
            echo "  -h, --help      Show this help message"
            exit 0
            ;;
        -*)
            err "Unknown option: $1"
            exit 1
            ;;
        *)
            if [[ -z "$N" ]]; then
                N="$1"
            else
                err "Unexpected argument: $1"
                exit 1
            fi
            shift
            ;;
    esac
done

if [[ -z "$N" ]]; then
    err "One argument expected: N - the number of .ris files to process."
    echo "Usage: $(basename "$0") [OPTIONS] N"
    exit 1
fi

# --- Timestamp for unique filenames ---
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
ISIFILE="/tmp/savedrecs.txt"

# --- Find .ris files (newest first, ignoring already-processed) ---
readarray -t RISFILES <<<"$(ls -t /tmp/*.ris --ignore "*-used.ris" 2>/dev/null)"

# Filter out empty entries
VALID_RISFILES=()
for f in "${RISFILES[@]}"; do
    [[ -n "$f" && -f "$f" ]] && VALID_RISFILES+=("$f")
done
RISFILES=("${VALID_RISFILES[@]}")

if [[ $VERBOSE -eq 1 ]]; then
    echo -e "${BLUE}All matching .ris files in /tmp${NC}"
    printf '  %s\n' "${RISFILES[@]}"
    echo "  Count: ${#RISFILES[@]}"
fi

if [[ "${#RISFILES[@]}" -lt "$N" ]]; then
    err "Requested $N .ris files but only ${#RISFILES[@]} found in /tmp/"
    exit 1
fi

# --- Take the first N ---
RISFILES=("${RISFILES[@]:0:N}")

if [[ $VERBOSE -eq 1 || $DRYRUN -eq 1 ]]; then
    echo -e "${BLUE}Processing $N .ris file(s):${NC}"
    printf '  %s\n' "${RISFILES[@]}"
fi

# --- Handle pre-existing ISI file ---
if [[ -f "$ISIFILE" ]]; then
    if [[ $BATCH -eq 1 ]]; then
        BACKUP="${ISIFILE}.${TIMESTAMP}.bak"
        warn "$ISIFILE exists, backing up to $BACKUP"
        if [[ $DRYRUN -eq 0 ]]; then
            mv "$ISIFILE" "$BACKUP"
        fi
    else
        echo "$ISIFILE already exists."
        echo -n "Remove file and continue? (n): "
        read TMP
        if [[ $TMP == "y" || $TMP == "Y" ]]; then
            echo "Removing $ISIFILE and continuing"
            rm "$ISIFILE"
        else
            echo "Leaving $ISIFILE untouched. Exiting..."
            exit 1
        fi
    fi
fi

# --- Convert RIS -> ISI ---
if [[ $DRYRUN -eq 1 ]]; then
    echo -e "${BLUE}[dry-run] Would convert ${#RISFILES[@]} .ris files to $ISIFILE${NC}"
else
    for FILE in "${RISFILES[@]}"; do
        [[ $VERBOSE -eq 1 ]] && echo -e "  Converting: $FILE"
        ris2xml "$FILE" | xml2isi -nb >> "$ISIFILE"
        if [[ $? -ne 0 ]]; then
            err "Failed to convert: $FILE"
        fi
    done
    ok "Created $ISIFILE from ${#RISFILES[@]} .ris file(s)"
fi

# --- Run prepend.bib.pl ---
if [[ $DRYRUN -eq 1 ]]; then
    echo -e "${BLUE}[dry-run] Would run prepend.bib.pl${NC}"
    [[ $BATCH -eq 1 ]] && echo -e "${BLUE}[dry-run]   with --batch flag${NC}"
else
    echo -e "\n${BLUE}Running prepend.bib.pl...${NC}"
    if [[ $BATCH -eq 1 ]]; then
        ~/bin/prepend.bib.pl --batch
    else
        ~/bin/prepend.bib.pl
    fi
fi

exit 0
