#!/usr/bin/env python3
# ============================================================================
# Script:       update.bib.py
# Version:      1.1.0
# Date:         2026-02-23
# Purpose:      Convert bibliography files to BibTeX, generate standardized
#               citation keys and PDF filenames, update master bibliography.
#
# Accepts .ris, .bib, .nbib, .end, .endx, .xml input files.
# Replaces the legacy isi2bibtex Perl pipeline with native Python parsing
# for .bib and .ris formats, and bibutils subprocess for other formats.
#
# Usage:        update.bib.py [OPTIONS] N
#               update.bib.py [OPTIONS] BIBFILE PDFFILE
#               update.bib.py [OPTIONS] FILE [FILE...]
#
# Input:        N (integer) -- process N newest bibliography files from
#                              staging directory (default: /tmp)
#               BIBFILE PDFFILE -- one bibliography file + one PDF (paired)
#               FILE...  -- one or more bibliography files
# Output:       Formatted BibTeX entries prepended to master bibliography.
#               PDFs moved to ~/References/ with symlinks in cwd.
#
# Options:
#   -n, --dry-run     Show what would be done without making changes
#   -v, --verbose     Show detailed output
#   -h, --help        Show this help message
#   -d, --dir DIR     Staging directory for batch mode (default: /tmp)
#   -f, --format FMT  Force input format (ris|bib|nbib|end|endx|xml)
#   --no-move         Skip PDF move/link step
#   --no-prepend      Skip prepending to master bibliography
#   --bib FILE        Master bibliography file
#                     (default: ~/BiBTeX/bibliography.full.bib)
#   --refs DIR        References directory (default: ~/References)
#
# Requirements:
#   - Python 3.9+
#   - rispy (pip install rispy) -- for .ris files
#   - bibtexparser (pip install bibtexparser) -- for .bib files
#   - bibutils suite (ris2xml, bib2xml, nbib2xml, etc.) -- for other formats
#
# Session:      BibTeX Tools Redesign
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

import argparse
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Optional imports -- graceful fallback to bibutils subprocess
# ---------------------------------------------------------------------------
try:
    import rispy
    HAS_RISPY = True
except ImportError:
    HAS_RISPY = False

try:
    import bibtexparser
    HAS_BIBTEXPARSER = True
except ImportError:
    HAS_BIBTEXPARSER = False

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Bibutils converters for formats without native Python support.
# Also used as fallback when rispy/bibtexparser are not installed.
BIBUTILS_CONVERTERS = {
    "ris": "ris2xml",
    "bib": "bib2xml",
    "nbib": "nbib2xml",
    "end": "end2xml",
    "endx": "endx2xml",
    "xml": None,  # already MODS XML, pipe directly to xml2bib
}

# Supported bibliography file extensions for batch mode discovery.
# Note: .xml is excluded from batch discovery because /tmp often contains
# unrelated XML files. Use explicit file mode for MODS XML input.
SUPPORTED_EXTENSIONS = {".ris", ".bib", ".nbib", ".end", ".endx"}

# Words whose case should be preserved in filenames and protected with {}
# in BibTeX titles. Entries are case-sensitive patterns.
# - ALL-CAPS entries (e.g., "DNA") are kept uppercase in filenames and
#   wrapped in {DNA} in BibTeX titles to prevent auto-lowercasing.
# - Mixed-case entries (e.g., "mRNA") are kept as-is in filenames and
#   wrapped in {mRNA} in BibTeX titles.
# Add new terms as needed -- this list is intentionally extensible.
PROTECTED_WORDS = [
    # Nucleic acids and sequences
    "DNA", "RNA", "mRNA", "tRNA", "rRNA", "siRNA", "miRNA", "snRNA",
    "snoRNA", "lncRNA", "ncRNA", "dsRNA", "ssRNA", "cDNA", "gDNA",
    "mtDNA", "cpDNA",
    # Proteins and enzymes
    "ATP", "ADP", "AMP", "GTP", "GDP", "GMP", "NAD", "NADH", "NADP",
    "NADPH", "FAD", "CoA",
    # Molecular biology techniques and terms
    "PCR", "qPCR", "RT-PCR", "CRISPR", "FISH", "FACS", "FRET",
    "ChIP", "EMSA", "ELISA", "GWAS", "QTL", "SNP", "SNPs",
    "HGT", "LGT",
    # Genomics and bioinformatics
    "ORF", "ORFs", "UTR", "CDS", "BAC", "YAC", "EST", "ESTs",
    "BLAST", "MCMC", "UPGMA", "HMM", "HMMs", "AIC", "BIC",
    "ML", "REML", "EM",
    # Organisms and model systems
    "HIV", "HPV", "SARS", "MERS",
    # Transposable elements (relevant to this bibliography)
    "TE", "TEs", "LINE", "LINEs", "SINE", "SINEs", "LTR", "LTRs",
    "Alu",
    # Evolution and population genetics
    "dN", "dS", "dN/dS", "Ka", "Ks", "Ka/Ks",
    "Ne",
    # Statistics
    "ANOVA", "PCA", "GLM", "GLMM",
    # Chemistry
    "pH", "CO2", "O2", "H2O", "NaCl",
    # General science
    "UV", "IR", "NMR", "MRI", "CT", "PET",
    "USA", "UK", "EU",
    # Taxonomic conventions (genus abbreviations commonly seen)
    # These are single letters followed by a period, handled separately
    # in the title protection logic (e.g., E. coli -> {E.} coli).
]

# Build a set for fast lookup and a regex pattern for word boundary matching
_PROTECTED_SET = set(PROTECTED_WORDS)
# Sort by length (longest first) so "mRNA" matches before "RNA"
_PROTECTED_PATTERN = re.compile(
    r'\b(' + '|'.join(re.escape(w) for w in
                      sorted(PROTECTED_WORDS, key=len, reverse=True)) + r')\b'
)

# Long journal name abbreviations
JOURNAL_ABBREVIATIONS = {
    "Proceedings Of The National Academy Of Sciences Of The United States Of America": "PNAS",
    "Proceedings of the National Academy of Sciences of the United States of America": "PNAS",
    "Proceedings Of The Royal Society B-Biological Sciences": "PRSB",
    "Proceedings of the Royal Society B-Biological Sciences": "PRSB",
    "Proceedings of the Royal Society B: Biological Sciences": "PRSB",
}

# Default paths
DEFAULT_BIB = Path.home() / "BiBTeX" / "bibliography.full.bib"
DEFAULT_REFS = Path.home() / "References"
DEFAULT_STAGING = Path("/tmp")


# ---------------------------------------------------------------------------
# BibTeX entry parsing
# ---------------------------------------------------------------------------

def parse_bibtex_string(text):
    """Parse BibTeX string into a list of entry dicts.

    Each dict has keys: entry_type, cite_key, and all BibTeX fields
    (author, title, year, journal, volume, pages, abstract, doi, pmid, etc.).

    Uses bibtexparser if available, otherwise falls back to regex parsing.
    """
    if HAS_BIBTEXPARSER:
        return _parse_with_bibtexparser(text)
    return _parse_with_regex(text)


def _parse_with_bibtexparser(text):
    """Parse BibTeX using the bibtexparser library.

    Supports both v1.x (BibTexParser class) and v2.x (parse function).
    """
    # v2 API: bibtexparser.parse()
    if hasattr(bibtexparser, 'parse'):
        library = bibtexparser.parse(text)
        entries = []
        for entry in library.entries:
            d = {"entry_type": entry.entry_type, "cite_key": entry.key}
            for field in entry.fields:
                d[field.key.lower()] = field.value
            entries.append(d)
        return entries

    # v1 API: bibtexparser.loads() with BibTexParser
    parser = bibtexparser.bparser.BibTexParser(common_strings=True)
    parser.ignore_nonstandard_types = False
    library = bibtexparser.loads(text, parser=parser)
    entries = []
    for entry in library.entries:
        d = {"entry_type": entry.get("ENTRYTYPE", "article"),
             "cite_key": entry.get("ID", "")}
        for key, value in entry.items():
            if key not in ("ENTRYTYPE", "ID"):
                d[key.lower()] = value
        entries.append(d)
    return entries


def _parse_with_regex(text):
    """Parse BibTeX using regex. Handles well-formed entries from bibutils
    and journal websites. Not a full parser -- does not handle nested braces
    in field values beyond one level."""
    entries = []
    # Match @type{key, ... }
    # Use a state machine approach for robustness with nested braces
    entry_starts = list(re.finditer(r'@(\w+)\s*\{', text))

    for idx, match in enumerate(entry_starts):
        entry_type = match.group(1).lower()
        start = match.end()

        # Find the matching closing brace by counting brace depth
        depth = 1
        pos = start
        while pos < len(text) and depth > 0:
            if text[pos] == '{':
                depth += 1
            elif text[pos] == '}':
                depth -= 1
            pos += 1
        body = text[start:pos - 1]

        # Extract cite key (everything before first comma)
        comma_pos = body.find(',')
        if comma_pos == -1:
            continue
        cite_key = body[:comma_pos].strip()
        fields_text = body[comma_pos + 1:]

        d = {"entry_type": entry_type, "cite_key": cite_key}

        # Parse fields: key = {value} or key = "value" or key = number
        field_pattern = re.compile(
            r'(\w[\w-]*)\s*=\s*'
            r'(?:\{((?:[^{}]|\{[^{}]*\})*)\}'  # {value with {nested}}
            r'|"([^"]*)"'                       # "value"
            r'|(\d+))',                          # bare number
            re.DOTALL,
        )
        for m in field_pattern.finditer(fields_text):
            key = m.group(1).lower()
            value = m.group(2) if m.group(2) is not None else (
                m.group(3) if m.group(3) is not None else m.group(4)
            )
            if value is not None:
                # Normalize whitespace
                value = re.sub(r'\s+', ' ', value).strip()
                d[key] = value

        entries.append(d)
    return entries


# ---------------------------------------------------------------------------
# RIS parsing
# ---------------------------------------------------------------------------

def parse_ris_file(filepath):
    """Parse a RIS file into a list of entry dicts with normalized field names.

    Uses rispy if available, otherwise falls back to bibutils subprocess.
    Returns dicts with the same field names as parse_bibtex_string().
    """
    if HAS_RISPY:
        return _parse_ris_with_rispy(filepath)
    return _parse_via_bibutils(filepath, "ris")


def _parse_ris_with_rispy(filepath):
    """Parse RIS using the rispy library."""
    with open(filepath, "r", encoding="utf-8", errors="replace") as f:
        ris_entries = rispy.load(f)

    entries = []
    for ris in ris_entries:
        d = {"entry_type": "article"}

        # Authors: rispy returns list of "Surname, Firstname" strings
        authors = ris.get("authors", ris.get("first_authors", []))
        if authors:
            d["author"] = " and ".join(authors)

        # Map RIS fields to BibTeX fields
        field_map = {
            "title": "title",
            "primary_title": "title",
            "secondary_title": "journal",
            "journal_name": "journal",
            "year": "year",
            "publication_year": "year",
            "volume": "volume",
            "start_page": "_start_page",
            "end_page": "_end_page",
            "abstract": "abstract",
            "doi": "doi",
            "notes": "pmid",  # PMID sometimes stored in notes
        }
        for ris_key, bib_key in field_map.items():
            val = ris.get(ris_key)
            if val and bib_key not in d:
                if isinstance(val, list):
                    val = "; ".join(str(v) for v in val)
                d[bib_key] = str(val)

        # Combine start/end pages
        sp = d.pop("_start_page", None)
        ep = d.pop("_end_page", None)
        if sp:
            d["pages"] = f"{sp}-{ep}" if ep else sp

        # Year extraction: rispy may return "2012/03/15" or "2012"
        if "year" in d:
            year_match = re.match(r'(\d{4})', str(d["year"]))
            if year_match:
                d["year"] = year_match.group(1)

        entries.append(d)
    return entries


# ---------------------------------------------------------------------------
# Generic format conversion via bibutils
# ---------------------------------------------------------------------------

def _parse_via_bibutils(filepath, fmt):
    """Convert any supported format to BibTeX via bibutils subprocess,
    then parse the resulting BibTeX."""
    converter = BIBUTILS_CONVERTERS.get(fmt)

    if fmt == "xml":
        # Already MODS XML, just pipe to xml2bib
        cmd = ["xml2bib", "-nb", filepath]
    elif converter:
        # Two-stage: format2xml | xml2bib
        cmd_str = f'{converter} "{filepath}" | xml2bib -nb'
        result = subprocess.run(
            cmd_str, shell=True, capture_output=True, text=True
        )
        if result.returncode != 0:
            print(f"ERROR: bibutils conversion failed for {filepath}",
                  file=sys.stderr)
            if result.stderr:
                print(f"  {result.stderr.strip()}", file=sys.stderr)
            return []
        return parse_bibtex_string(result.stdout)
    else:
        print(f"ERROR: no converter for format '{fmt}'", file=sys.stderr)
        return []

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ERROR: bibutils conversion failed for {filepath}",
              file=sys.stderr)
        return []
    return parse_bibtex_string(result.stdout)


def convert_file_to_entries(filepath, fmt=None):
    """Convert a bibliography file to a list of entry dicts.

    Auto-detects format from extension if fmt is not specified.
    Uses native Python libraries for .bib and .ris when available.
    Falls back to bibutils subprocess for all other formats.
    """
    filepath = str(filepath)
    if fmt is None:
        ext = os.path.splitext(filepath)[1].lower().lstrip(".")
    else:
        ext = fmt.lower()

    if ext == "bib":
        with open(filepath, "r", encoding="utf-8", errors="replace") as f:
            text = f.read()
        return parse_bibtex_string(text)
    elif ext == "ris":
        return parse_ris_file(filepath)
    elif ext in BIBUTILS_CONVERTERS:
        return _parse_via_bibutils(filepath, ext)
    else:
        print(f"WARNING: unrecognized format '.{ext}' for {filepath} "
              f"-- skipping", file=sys.stderr)
        return []


# ---------------------------------------------------------------------------
# Author name handling
# ---------------------------------------------------------------------------

def parse_authors(author_str):
    """Parse a BibTeX author string into a list of (surname, firstnames) tuples.

    Handles formats:
        "Surname, F. and Surname2, G. H."
        "Surname, Firstname and Surname2, Firstname2"
        "F. Surname and G. Surname2"  (rare but possible)
    """
    if not author_str:
        return []

    # Split on " and " (BibTeX standard separator)
    parts = re.split(r'\s+and\s+', author_str)
    authors = []
    for part in parts:
        part = part.strip()
        if not part:
            continue
        if "," in part:
            # "Surname, Firstnames" format (most common)
            surname, _, firstnames = part.partition(",")
            surname = surname.strip()
            firstnames = firstnames.strip()
        else:
            # "Firstnames Surname" format -- last token is surname
            tokens = part.split()
            if len(tokens) >= 2:
                surname = tokens[-1]
                firstnames = " ".join(tokens[:-1])
            else:
                surname = part
                firstnames = ""
        # Title-case surname if all caps
        if surname == surname.upper() and len(surname) > 1:
            surname = _title_case_surname(surname)
        # Reduce firstnames to initials
        firstnames = _to_initials(firstnames)
        authors.append((surname, firstnames))
    return authors


def _title_case_surname(name):
    """Title-case a surname with special handling for Mc/Mac/O' prefixes."""
    name = name.title()
    # Fix Mc/Mac/O' prefixes: McDonald, MacArthur, O'Brien
    name = re.sub(r"^(Mc|Mac|O')([a-z])", lambda m: m.group(1) + m.group(2).upper(), name)
    return name


def _to_initials(firstnames):
    """Convert firstnames to initials: 'John Michael' -> 'J. M.'"""
    if not firstnames:
        return ""
    # If already initials like "J. M.", normalize spacing
    # Remove lowercase letters (keep only uppercase initials)
    initials = re.findall(r'[A-Z]', firstnames)
    if initials:
        return ". ".join(initials) + "."
    # Edge case: all lowercase (shouldn't happen, but be safe)
    words = firstnames.split()
    return ". ".join(w[0].upper() for w in words if w) + "." if words else ""


# ---------------------------------------------------------------------------
# Key and filename generation
# ---------------------------------------------------------------------------

def generate_key(authors, year):
    """Generate a BibTeX citation key from authors and year.

    1 author:   Surname + Year         -> Smith2012
    2 authors:  Surname1AndSurname2Year -> SmithAndJones2012
    3+ authors: Surname1EtAlYear       -> SmithEtAl2012
    """
    if not authors:
        return f"Unknown{year}"
    if len(authors) == 1:
        key = authors[0][0]
    elif len(authors) == 2:
        key = f"{authors[0][0]}And{authors[1][0]}"
    else:
        key = f"{authors[0][0]}EtAl"
    # Remove spaces and non-alphanumeric chars from key
    key = re.sub(r'[^A-Za-z0-9]', '', key)
    return f"{key}{year}"


def generate_filename(authors, year, title, journal):
    """Generate a standardized PDF filename.

    Format: Author(s)_YYYY_title.words_Journal.Name.pdf

    1 author:   Smith_2012_title.words_Journal.pdf
    2 authors:  Smith.and.Jones_2012_title.words_Journal.pdf
    3+ authors: Smith.et.al_2012_title.words_Journal.pdf
    """
    # Build author stem
    if not authors:
        author_stem = "Unknown"
    elif len(authors) == 1:
        author_stem = authors[0][0]
    elif len(authors) == 2:
        author_stem = f"{authors[0][0]}.and.{authors[1][0]}"
    else:
        author_stem = f"{authors[0][0]}.et.al"

    # Process title
    title = _clean_title_for_filename(title or "untitled")

    # Process journal
    journal = _clean_journal_for_filename(journal or "")

    # Assemble
    if journal:
        filename = f"{author_stem}_{year}_{title}_{journal}.pdf"
    else:
        filename = f"{author_stem}_{year}_{title}.pdf"

    # Final cleanup
    filename = _sanitize_filename(filename)
    return filename


def _clean_title_for_filename(title):
    """Clean a title for use in a filename.

    Lowercases most title words but preserves protected words like DNA,
    mRNA, CRISPR, etc. whose case is significant.
    """
    # Remove trailing period
    title = title.rstrip(".")
    # Remove apostrophes
    title = title.replace("'", "")

    # Temporarily replace protected words with placeholders to prevent
    # the lowercasing regex from touching them
    placeholders = {}
    def _protect(m):
        token = f"\x00PW{len(placeholders)}\x00"
        placeholders[token] = m.group(0)
        return token
    title = _PROTECTED_PATTERN.sub(_protect, title)

    # Lowercase words that start with a single capital letter followed by
    # a lowercase letter or space (preserves all-caps acronyms).
    # Matches the Perl: s/\b([A-Z][ a-z])/ lc($1)/eg
    title = re.sub(
        r'\b([A-Z])([ a-z])',
        lambda m: m.group(1).lower() + m.group(2),
        title
    )

    # Restore protected words
    for token, original in placeholders.items():
        title = title.replace(token, original)

    return title


def _clean_journal_for_filename(journal):
    """Clean a journal name for use in a filename."""
    if not journal:
        return ""
    # Apply abbreviations for long journal names
    for full_name, abbrev in JOURNAL_ABBREVIATIONS.items():
        if journal.lower() == full_name.lower():
            journal = abbrev
            break
    # Replace & with "and"
    journal = journal.replace("&", "and")
    # Fix PLoS casing
    journal = re.sub(r'^Plos\.?', 'PLoS.', journal, flags=re.IGNORECASE)
    return journal


def _sanitize_filename(filename):
    """Sanitize a filename: replace special chars, collapse separators."""
    # Replace spaces, commas, parentheses with periods
    filename = re.sub(r'[ ,()]+', '.', filename)
    # Replace colons, semicolons, slashes, question marks, exclamation
    # marks (optionally followed by a period) with hyphens
    filename = re.sub(r'[-:/;?!]+\.?', '-', filename)
    # Fix separator before underscore: -_ or ._ -> _
    filename = re.sub(r'[-._]_', '_', filename)
    # Remove any remaining non-word characters (keep . - _)
    filename = re.sub(r'[^\w._-]', '', filename)
    # Collapse multiple periods
    filename = re.sub(r'\.{2,}', '.', filename)
    # Collapse multiple hyphens
    filename = re.sub(r'-{2,}', '-', filename)
    return filename


# ---------------------------------------------------------------------------
# BibTeX title protection
# ---------------------------------------------------------------------------

def protect_bibtex_title(title):
    """Wrap protected words in {} to prevent BibTeX from lowercasing them.

    Examples:
        "DNA replication in E. coli" -> "{DNA} replication in {E.} coli"
        "Analysis of mRNA stability"  -> "Analysis of {mRNA} stability"

    Words already wrapped in braces are left alone.
    """
    if not title:
        return title

    # Protect known acronyms/terms from the PROTECTED_WORDS list
    def _wrap(m):
        word = m.group(0)
        # Check if already inside braces by looking at surrounding context
        start = m.start()
        if start > 0 and title[start - 1] == '{':
            return word  # already protected
        return '{' + word + '}'

    result = _PROTECTED_PATTERN.sub(_wrap, title)
    return result


# ---------------------------------------------------------------------------
# BibTeX output formatting
# ---------------------------------------------------------------------------

def format_bibtex_entry(entry, key, filename, refs_dir):
    """Format a single BibTeX entry with standardized field order.

    Matches the existing format in bibliography.full.bib:
    tabs for indentation, specific field ordering, file = {} field.
    Protected words in the title are wrapped in {} to prevent BibTeX
    from auto-lowercasing them.
    """
    entry_type = entry.get("entry_type", "article")
    fullpath = os.path.join(str(refs_dir), filename)

    # Get timestamp
    now = datetime.now()
    timestamp = f"{now.year}.{now.month}.{now.day}"

    lines = [f"@{entry_type}{{{key},"]

    # Field order matching existing bibliography.full.bib
    field_order = [
        ("author", "author"),
        ("title", "title"),
        ("journal", "journal"),
        ("journal-iso", "journal-iso"),
        ("keywords", "keywords"),
        ("year", "year"),
        ("volume", "volume"),
        ("pages", "pages"),
        ("abstract", "abstract"),
    ]

    # Compute alignment: field names are padded, values use tab alignment
    for display_name, field_key in field_order:
        value = entry.get(field_key, entry.get(display_name, ""))
        if value is None:
            value = ""
        # Clean up "ER" artifacts from ISI conversion
        value = re.sub(r'\s*ER\s*$', '', str(value))
        # Protect case-sensitive words in title field
        if display_name == "title":
            value = protect_bibtex_title(value)
        padding = " " * max(1, 12 - len(display_name))
        lines.append(f"\t{display_name}{padding}= {{{value}}},")

    # file field
    lines.append(f"\tfile\t= {{{fullpath}:PDF}},")

    # timestamp
    lines.append(f"\ttimestamp  = {{{timestamp}}},")

    # pmid
    pmid = entry.get("pmid", "")
    if pmid:
        pmid = re.sub(r'\s*ER\s*$', '', str(pmid))
    lines.append(f"\tpmid\t   = {{{pmid}}},")

    # doi (last field, no trailing comma)
    doi = entry.get("doi", "")
    if doi:
        doi = re.sub(r'\s*ER\s*$', '', str(doi))
        lines.append(f"\tdoi\t  = {{{doi}}}")
    else:
        # Remove trailing comma from pmid line
        lines[-1] = lines[-1].rstrip(",")

    lines.append("}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# File operations
# ---------------------------------------------------------------------------

def backup_and_prepend(new_text, bib_path, dry_run=False, verbose=False):
    """Prepend new BibTeX entries to the master bibliography file.

    Backup chain:
    1. Bkups/bibliography.full.bib -> Bkups/bibliography.full.bkup
    2. bibliography.full.bib -> Bkups/bibliography.full.bib
    3. new_text + old content -> bibliography.full.bib
    """
    bib_path = Path(bib_path)
    bkups_dir = bib_path.parent / "Bkups"

    if not bib_path.exists():
        print(f"WARNING: {bib_path} does not exist. Will create it.",
              file=sys.stderr)
        if dry_run:
            print(f"[dry-run] Would create {bib_path}")
            return
        bib_path.parent.mkdir(parents=True, exist_ok=True)
        with open(bib_path, "w", encoding="utf-8") as f:
            f.write(new_text + "\n")
        return

    if dry_run:
        print(f"[dry-run] Would prepend {len(new_text)} chars to {bib_path}")
        return

    # Create backup directory if needed
    bkups_dir.mkdir(parents=True, exist_ok=True)

    bib_name = bib_path.name
    bkup_path = bkups_dir / bib_name
    bkup2_path = bkups_dir / bib_name.replace(".bib", ".bkup")

    # Rotate backups
    if bkup_path.exists():
        shutil.copy2(str(bkup_path), str(bkup2_path))
    shutil.copy2(str(bib_path), str(bkup_path))

    # Read existing content and prepend
    with open(bib_path, "r", encoding="utf-8") as f:
        existing = f.read()
    with open(bib_path, "w", encoding="utf-8") as f:
        f.write(new_text + "\n\n" + existing)

    if verbose:
        print(f"Prepended to {bib_path} (backup in {bkups_dir})")


def move_and_link_pdf(src_pdf, dest_filename, refs_dir, dry_run=False,
                      verbose=False):
    """Copy PDF to refs_dir with standardized name, create symlink in cwd.

    Args:
        src_pdf: Path to the source PDF file
        dest_filename: Standardized filename (e.g., Smith.et.al_2012_..._Journal.pdf)
        refs_dir: Target directory (default ~/References)
        dry_run: If True, only print what would be done
        verbose: If True, print detailed output
    """
    src = Path(src_pdf)
    dest = Path(refs_dir) / dest_filename
    link = Path.cwd() / dest_filename

    if not src.exists():
        print(f"ERROR: PDF not found: {src}", file=sys.stderr)
        return False

    if dry_run:
        print(f"[dry-run] Would copy {src} -> {dest}")
        print(f"[dry-run] Would symlink {link} -> {dest}")
        return True

    # Copy PDF to references directory
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(str(src), str(dest))
    if verbose:
        print(f"Copied {src} -> {dest}")

    # Create symlink in current directory
    if link.exists() or link.is_symlink():
        if verbose:
            print(f"Symlink already exists: {link}")
    else:
        link.symlink_to(dest)
        if verbose:
            print(f"Symlinked {link} -> {dest}")

    return True


# ---------------------------------------------------------------------------
# Batch mode file discovery
# ---------------------------------------------------------------------------

def find_bib_files(directory, n, verbose=False):
    """Find the N newest bibliography files in directory.

    Excludes files matching *-used* (already processed).
    Returns list of Path objects sorted by mtime (newest first).
    """
    directory = Path(directory)
    if not directory.is_dir():
        print(f"ERROR: staging directory not found: {directory}",
              file=sys.stderr)
        return []

    candidates = []
    for f in directory.iterdir():
        if not f.is_file():
            continue
        if f.suffix.lower() not in SUPPORTED_EXTENSIONS:
            continue
        if "-used" in f.name:
            continue
        candidates.append(f)

    # Sort by modification time, newest first
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)

    if verbose:
        print(f"Found {len(candidates)} bibliography files in {directory}")
        for c in candidates[:10]:
            print(f"  {c.name}")

    if len(candidates) < n:
        print(f"ERROR: requested {n} files but only found {len(candidates)} "
              f"in {directory}", file=sys.stderr)
        return []

    return candidates[:n]


# ---------------------------------------------------------------------------
# Mode detection
# ---------------------------------------------------------------------------

def detect_mode(args):
    """Determine operating mode from positional arguments.

    Returns: (mode, details) where mode is one of:
        "batch"  -- details is int N
        "paired" -- details is (bibfile, pdffile)
        "files"  -- details is list of file paths
    """
    if len(args) == 1:
        # Single argument: integer -> batch, file -> single file
        if args[0].isdigit():
            return ("batch", int(args[0]))
        return ("files", [args[0]])

    if len(args) == 2:
        # Two arguments: check if one is a PDF
        a, b = args
        a_is_pdf = a.lower().endswith(".pdf")
        b_is_pdf = b.lower().endswith(".pdf")

        if a_is_pdf and not b_is_pdf:
            return ("paired", (b, a))  # (bibfile, pdffile)
        if b_is_pdf and not a_is_pdf:
            return ("paired", (a, b))  # (bibfile, pdffile)
        # Neither or both are PDFs -- treat as file list
        return ("files", list(args))

    # 3+ arguments: file list mode
    return ("files", list(args))


# ---------------------------------------------------------------------------
# Dependency checking
# ---------------------------------------------------------------------------

def check_dependencies(formats_needed, verbose=False):
    """Check that required tools are available for the given formats.

    Returns True if all dependencies are met, False otherwise.
    """
    ok = True

    # Check for native Python libraries
    if "ris" in formats_needed and not HAS_RISPY:
        if not shutil.which("ris2xml") or not shutil.which("xml2bib"):
            print("ERROR: rispy not installed and bibutils (ris2xml, xml2bib) "
                  "not found. Install rispy: pip install rispy", file=sys.stderr)
            ok = False
        elif verbose:
            print("NOTE: rispy not installed, using bibutils for .ris files")

    if "bib" in formats_needed and not HAS_BIBTEXPARSER:
        if verbose:
            print("NOTE: bibtexparser not installed, using built-in parser")

    # Check bibutils for formats that always need it
    bibutils_formats = formats_needed - {"ris", "bib"}
    if ("ris" in formats_needed and not HAS_RISPY):
        bibutils_formats.add("ris")

    for fmt in bibutils_formats:
        converter = BIBUTILS_CONVERTERS.get(fmt)
        if converter and not shutil.which(converter):
            print(f"ERROR: {converter} not found (needed for .{fmt} files). "
                  f"Install bibutils.", file=sys.stderr)
            ok = False
        if not shutil.which("xml2bib"):
            print("ERROR: xml2bib not found. Install bibutils.",
                  file=sys.stderr)
            ok = False
            break

    return ok


# ---------------------------------------------------------------------------
# Main processing
# ---------------------------------------------------------------------------

def process_entry(entry, refs_dir, pdf_path=None, dry_run=False,
                  verbose=False, no_move=False):
    """Process a single bibliography entry.

    Generates key and filename, optionally moves PDF.
    Returns (formatted_bibtex, key, filename) tuple.
    """
    authors = parse_authors(entry.get("author", ""))
    year = entry.get("year", "0000")
    title = entry.get("title", "")
    journal = entry.get("journal", "")

    key = generate_key(authors, year)
    filename = generate_filename(authors, year, title, journal)

    if verbose:
        print(f"  Key:      {key}")
        print(f"  Filename: {filename}")

    formatted = format_bibtex_entry(entry, key, filename, refs_dir)

    if pdf_path and not no_move:
        move_and_link_pdf(pdf_path, filename, refs_dir,
                          dry_run=dry_run, verbose=verbose)

    return formatted, key, filename


def run(args):
    """Main execution logic."""
    # Parse arguments
    parser = argparse.ArgumentParser(
        prog="update.bib.py",
        description="Convert bibliography files to BibTeX with standardized "
                    "citation keys and PDF filenames.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
modes:
  update.bib.py N                  Batch: process N newest files from /tmp
  update.bib.py BIBFILE PDFFILE    Paired: one bib file + one PDF
  update.bib.py FILE [FILE...]     Multi-file: process named bib files

examples:
  update.bib.py 3                  Process 3 newest .ris/.bib files from /tmp
  update.bib.py paper.ris paper.pdf   Convert RIS, rename+move PDF
  update.bib.py --dry-run ref1.bib ref2.ris   Preview without changes
""",
    )
    parser.add_argument("positional", nargs="*",
                        help="N (batch count) or FILE [FILE...] or "
                        "BIBFILE PDFFILE")
    parser.add_argument("-n", "--dry-run", action="store_true",
                        help="Show what would be done without making changes")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Show detailed output")
    parser.add_argument("-d", "--dir", default=str(DEFAULT_STAGING),
                        help=f"Staging directory for batch mode "
                        f"(default: {DEFAULT_STAGING})")
    parser.add_argument("-f", "--format",
                        choices=list(BIBUTILS_CONVERTERS.keys()),
                        help="Force input format instead of auto-detecting")
    parser.add_argument("--no-move", action="store_true",
                        help="Skip PDF move/link step")
    parser.add_argument("--no-prepend", action="store_true",
                        help="Skip prepending to master bibliography")
    parser.add_argument("--bib", default=str(DEFAULT_BIB),
                        help=f"Master bibliography file "
                        f"(default: {DEFAULT_BIB})")
    parser.add_argument("--refs", default=str(DEFAULT_REFS),
                        help=f"References directory (default: {DEFAULT_REFS})")

    opts = parser.parse_args(args)

    if not opts.positional:
        parser.print_help()
        return 1

    # Detect mode
    mode, details = detect_mode(opts.positional)

    if opts.verbose:
        print(f"Mode: {mode}")
        libs = []
        if HAS_RISPY:
            libs.append("rispy")
        if HAS_BIBTEXPARSER:
            libs.append("bibtexparser")
        if libs:
            print(f"Python libraries: {', '.join(libs)}")
        else:
            print("Python libraries: none (using bibutils + built-in parser)")

    # Gather files to process
    if mode == "batch":
        n = details
        bib_files = find_bib_files(opts.dir, n, verbose=opts.verbose)
        if not bib_files:
            return 1
        pdf_path = None
    elif mode == "paired":
        bib_file, pdf_path = details
        bib_files = [Path(bib_file)]
        if not Path(pdf_path).exists():
            print(f"ERROR: PDF not found: {pdf_path}", file=sys.stderr)
            return 1
    else:  # files mode
        bib_files = [Path(f) for f in details]
        pdf_path = None

    # Determine formats needed and check dependencies
    formats_needed = set()
    for f in bib_files:
        ext = opts.format or f.suffix.lower().lstrip(".")
        formats_needed.add(ext)

    if not check_dependencies(formats_needed, verbose=opts.verbose):
        return 1

    # Process each file
    all_formatted = []
    for bib_file in bib_files:
        if not Path(bib_file).exists():
            print(f"ERROR: file not found: {bib_file}", file=sys.stderr)
            return 1

        if opts.verbose:
            print(f"\nProcessing: {bib_file}")

        entries = convert_file_to_entries(bib_file, fmt=opts.format)
        if not entries:
            print(f"WARNING: no entries parsed from {bib_file}",
                  file=sys.stderr)
            continue

        for i, entry in enumerate(entries):
            if opts.verbose:
                print(f"\nEntry {i + 1}/{len(entries)}:")

            # In paired mode, only associate PDF with first entry
            entry_pdf = pdf_path if (mode == "paired" and i == 0) else None

            formatted, key, filename = process_entry(
                entry, opts.refs, pdf_path=entry_pdf,
                dry_run=opts.dry_run, verbose=opts.verbose,
                no_move=opts.no_move,
            )
            all_formatted.append(formatted)

            print(f"  {key}: {filename}")

    if not all_formatted:
        print("No entries to process.", file=sys.stderr)
        return 1

    # Combine all formatted entries
    combined = "\n\n".join(all_formatted)

    if opts.dry_run:
        print(f"\n--- Generated BibTeX ({len(all_formatted)} entries) ---")
        print(combined)
        print("---")

    # Prepend to master bibliography
    if not opts.no_prepend:
        backup_and_prepend(combined, opts.bib,
                           dry_run=opts.dry_run, verbose=opts.verbose)
    elif opts.verbose:
        print("Skipping prepend (--no-prepend)")

    # In batch mode, offer to process PDFs
    if mode == "batch" and not opts.no_move and not opts.dry_run:
        print(f"\n{len(all_formatted)} entries processed.")
        print("Use bib.move.and.link.sh to associate PDFs with entries,")
        print("or re-run in paired mode: update.bib.py BIBFILE PDFFILE")

    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    sys.exit(run(sys.argv[1:]))
